MPK,(SFO)IOCS,(SFO)IOCSU+<(RDO)STRLIB,(SFO)PF,(SFO)PFU+(CD)CCOM>
(SFO)IOCSU+(CD)SFORWU+(SFO)PFU+(CD)CCOMU+DBG
(SFO)IOCSU+(CD)STRNGU+(CD)SFORW,(SFO)IOCSU+(CD)SFORWU+(CD)STRNGU+(CD)ISFOIO
(SFO)IOCSU+(CD)STRNG,(CD)MSYM
