; THIS BATCH CONTROL FILE ERASES NON-ESSENTIAL FILES
;
; ERASE COMPILER MACRO FILES (EXCEPT GETBKT)
.DEL *.FAS
;
; ERASE ALL .REL FILES EXCEPT FASLIB
.RENAME FASLIB.LIB=FASLIB.REL
.DEL *.REL
.RENAME FASLIB.REL=FASLIB.LIB
