

RESPONSE TO DEVELOPMENT REQUEST # 73143:

IT IS INCONCEIVABLE THAT ANYONE KNOWING AND WORKING WITH THE
TYMCOM-X SYSTEM CAN NOT REMEMBER THE SEVEN HEADINGS OF THE ITEMS
PRINTED BY THE DIRECTORY COMMAND. IF THE INDIVIDUAL DOES NOT
UNDERSTAND THE SYSTEM, HE SHOULD BE USING THE FILES COMMAND,
WHICH PRINTS A MUCH ABBREVIATED LIST OF FILE NAMES AND EXTENTIONS.


HOWEVER, IF ONE MUST PERSIST, THIS FEATURE IS AVAILABLE AS FOLLOWS:

-DIR DIR.TMP=

-TYPE DIR.TMP

DIRECTORY [GAN,PPN]     [TIME]  [DATE]
   FILE                 CREATION                      ACCESS
NAME    EXT  BLOCKS    DATE    TIME      ALLOWED       DATE

TEST    CBL      15  10-MAY-73 1418    ALL RD  RD   14-MAY-73
