      SUBROUTINE OCTL (IA,IB)
      DIMENSION IB(6)
      J = IA
      DO 10 I=1,6
      K=7-I
      IB(K)= IAND(J,7)
      J= IRIGHT(J,3)
   10 CONTINUE
      IB(1)= IAND(IB(1),1)
      RETURN
      END
      SUBROUTINE OPDEF( IVALUE )
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON /XLIT/ NOLIST,EQFLG
      LOGICAL NOLIST,EQFLG
C
C
C			     GET WHICH OP DEF INST.
      IOCLAS = 4
      NWDS = 0
      IF( SKPFLG ) RETURN
      IF (EQFLG) GO TO 100
      J = IAND( IVALUE, 7)
C			     GET NEW OP NAME  IF( NULL ) ERROR
      CALL GETSYM( NAME )
      IF( NAME .EQ. 0 ) GO TO 50
C			     CHECK BREAK CHAR IS =
      IF( LN(ICH) .NE. IEQLS ) GO TO 50
C			     ONLY DEFINE ON PASS1
C
C
C			     SKIP OVER = SET CHAR CTR IN CASE EXPRESS.
      ICH = ICH +1
  100 LICH = ICH
C			     GET FIRST ELEMENT OF VARIABLE FIELD
      CALL GETSYM( IOP )
C			     CHECK IF OP CODE
      CALL OPLOOK( IOP, IV, IT )
      IF( IT .GE. 24 ) GO TO 50
      IT = IT -7
      IF( IT .GT. 8 ) IT = IT-8
C			     BRANCH TO PROPER HANDLER
      GO TO ( 21, 22, 23, 24, 25, 26, 27, 28 ),IT
C			     EXPRESSION ONLY
   21 ICH = LICH
      CALL EXPRES( IV,ITP, MD)
      IF (INDRCT .NE. 0) IV = IOR (IV,32768)
      IF (INOLOD .NE. 0) IV = IOR (IV,8)
      IV= IAND( 65536+IV ,  65535 )
      IF (EQFLG .AND. MD.EQ.1) GO TO 30
      IF( ITP.NE.1 .OR. MD.NE.1 ) GO TO 50
      GO TO 30
C
C			     ALC
   22 CALL TYPE1( IV, ITP)
      GO TO 30
C			     INST/AC
   23 CALL TYPE2( IV, ITP)
      GO TO 30
C			     I/O
   24 CALL TYPE3( IV,ITP)
      GO TO 30
C			     I/O/AC
 25   CALL TYPE4(IV, ITP)
      GO TO 30
C			     MREF
   26 CALL TYPE5( IV,ITP)
      GO TO 30
C			     MREF/AC
   27 CALL TYPE6( IV,ITP)
      GO TO 30
C			     USER
   28 CALL TYPE7( IV,ITP)
C
C
   30 CONTINUE
      IOCLAS = 3
      NWDS = 0
      IWORD(1) = IV
      IWTYPE=ITP
      IF (EQFLG) GO TO 200
      IF( IWTYPE .NE. 1 ) CALL ERROR(1HR)
      IWTYPE = 1
C			     FIND NAME IN OP TABLE AND INSERT VALUE
C			     FOUND IT SET VALUE AND OUTPUT CLASS
      IF( PASS1 ) CALL ADDSYM(NAME, IV, J+40)
      RETURN
C
C			     COMPLETE ERROR SET TO TREAT LIKE COMMENT.
   50 CONTINUE
      CALL ERROR( 1HQ )
      IV = 0
      GO TO 30
C
  200 CALL ADDSYM (LABEL, IV, ITP)
      RETURN
      END
      SUBROUTINE OPLOOK( IOP, IVALUE, ITYPE)
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     RETURN TABLE VALUE AND TYPE
C			     LOOK UP IOP IN OPCODE TABLE
      IVALUE = 0
      ITYPE = 8
C			     ASSUME EXPRESSION
      IF( IOP .EQ. 0 ) RETURN
CIF PERIOD, DO NOT SEARCH TABLE
      IF (LNX(1).EQ.IPRD .AND. NLNX.EQ.1) RETURN
C			     SEARCH OP TABLE
      CALL LOOKUP( IOP, IVALUE, ITP )
C			     SET AS EXPRESSION IF ITP IS SYMBOL
      IF( ITP	.LE. 7	)  RETURN
C			     ITS OP CODE RESET TYPE
      ITYPE = ITP
      RETURN
      END
      SUBROUTINE OPPROC( ITYPE, IVALUE)
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON /XLIT/ NOLIST,EQFLG
      LOGICAL NOLIST,EQFLG
C
C
C
C			     PROCESS OP CODE SUBROUTINE
      LOCNXT = LOCCNT
      IF( ITYPE .NE. 8 ) GO TO 10
      CALL EXPRES( IVAL, ITP, MODE)
C			     IF( 2 WORD FP OR DP ) ADD 1 TO NEXT LOC
      IWTYPE = ITP
      IVAL = IOR( IVAL, INDRCT)
      NWDS = 1
      IWORD(1) = IVAL
      IF( MODE .EQ. 1 ) GO TO 20
      LOCNXT = LOCNXT + 1
      IWORD(1) = IRIGHT(IVAL,16)
      IWORD(2) = IAND(IVAL, 65535)
      NWDS = 2
      GO TO 20
C			     REGULAR OP CODE
   10 CONTINUE
C			     IF( PSUEDO OP)
      IF( ITYPE .EQ. 24 ) GO TO 50
      IF( PASS1 ) GO TO 20
      IF( ITYPE .GT. 24 ) GO TO 30
      J = ITYPE - 8
      IF( ITYPE .GT. 16 ) J = J-8
C			     SET FLOATING PT TO CORRESP NORMAL OP CODE
C			     BRANCH TO HANDLER
      GO TO( 11,12,13,14,15,16,17 ) ,J
C			     PROCESS  ALC. FALC
   11 CALL TYPE1( IVALUE, ITYPE)
      GO TO 20
C			     PROCESS  INST/AC	FINST/AC
   12 CALL TYPE2( IVALUE, ITYPE)
      GO TO 20
C			     PROCESS  IO
   13 CALL TYPE3( IVALUE, ITYPE)
      GO TO 20
C			     PROCESS  IO/AC
   14 CALL TYPE4( IVALUE, ITYPE)
      GO TO 20
C			     PROCESS  MREF   FMREF
   15 CALL TYPE5( IVALUE, ITYPE)
      GO TO 20
C			     PROCESS  MREF/AC  FMREF/AC
   16 CALL TYPE6( IVALUE, ITYPE)
      GO TO 20
C			     PROCESS USER   FIXED
   17 CALL TYPE7( IVALUE, ITYPE)
      GO TO 20
C			     BUMP LOC NEXT  BY 1
   20 CONTINUE
      CODE = .TRUE.
      IOCLAS = 1
      LOCNXT = LOCNXT + 1
      CALL ADDSYM(LABEL,LOCCNT,IMODE)
C			     DONE  VALUE RETURNED IN IVALUE TYPE THRU IT
      RETURN
C
 30   CONTINUE
      IWTYPE = ITYPE - 24
      NWDS = 1
      IWORD(1) = IVALUE
      CALL ADDREF
      CALL CAREND
      GO TO 20
C
C
C
C			     PROCESS PSUEDO OPS GET CLASS OF PSUEDO
   50 CONTINUE
      J = IVALUE/16
C			     BRANCH ON CLASS
      GO TO ( 51, 52, 53, 54, 55, 56, 57, 58, 59, 591), J
C			     .END  .EOT  .XPNG
   51 CALL ENDS( IVALUE,ITYPE)
      CALL NOTAT
      CALL NONOLD
      GO TO 60
C			     .DALC  ETC.
   52 CALL OPDEF( IVALUE)
      GO TO 60
C			     .IFE .IFN .ENDC
   53 CALL IFS( IVALUE)
      CALL NOTAT
      CALL NONOLD
      GO TO 60
C			     .TXTM .TXT .TXTE,O,F
   54 CALL TEXTS( IVALUE)
      CALL NOTAT
      CALL NONOLD
      GO TO 60
C			     .BLK
   55 CALL BLOCK( IVALUE)
      GO TO 60
C			     .RADX
   56 CALL RADX( IVALUE)
      CALL NOTAT
      CALL NONOLD
      GO TO 60
C			     .ENT .EXTN .EXTD
   57 CALL EXTRNL( IVALUE, ITYPE)
      GO TO 60
C			     .TITL
   58 CALL TITLE( IVALUE )
      CALL NOTAT
      CALL NONOLD
      GO TO 60
C			     .LOC  .NREL  .ZREL
   59 CALL LOCATS( IVALUE, ITYPE)
      CALL NOTAT
      CALL NONOLD
      GO TO 60
  591 CONTINUE
C
C			     HANDLES = STATEMENTS
      EQFLG = .TRUE.
      CALL OPDEF (IVALUE)
      EQFLG = .FALSE.
C
C			     LOCATION CTR HANDLED BY SUBRTNS
   60 CONTINUE
C
C
      RETURN
      END
      SUBROUTINE OUTLOS
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     OUTPUT THE LOCAL SYMBOLS
C			     RETURN IF NOT ASKED FOR
      IF( .NOT.LOCALS .OR. PASS1 .OR. .NOT.PTAPE ) RETURN
C			     START THE LOCAL BLOCK
      CALL STRBLK(8 )
C			     SEARCH THE SYMBOL TABLE
C			     NOTE THE LOCALS ARE OUTPUT IN ALPHA ORDER
      DO 10 I=1,NSYM
      J = SYTYPE(I)
      K = IAND(J,31)
      IF( K.LE.0 .OR. K.GT.5 ) GO TO 10
      KI = IAND(J,32)
      IF (KI.NE.0) GO TO 10
      L = SYVALU(I)
      CALL ADSBLK( SYNAME(I),8,L,K)
 10   CONTINUE
C			     CLEAR THE OUTPUT BLOCK
      CALL PUTBLK
      RETURN
      END
      SUBROUTINE OUTNEX
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     OUTPUT THE NORMAL EXTERNAL DATA BLOCKS
C			     IF( .NOT. PTAPE .OR. PASS1 ) RETURN
      IF( PASS1 .OR. .NOT. PTAPE ) RETURN
C			     START AN EXTERN BLOCK
      CALL STRBLK( 5)
C
C			     SEARCH THE SYMBOL TABLE FOR NORMAL EXTRNS
      DO 10 I=1,NSYM
      J = SYTYPE(I)
      J = IAND(J,31)
C			     FOUND A NOR EXT
      IF( J .LE. 24 ) GO TO 10
      JADR = SYVALU(I)
      JTYP = J - 24
      JJ = SYVALU(I)
C
      CALL ADSBLK( SYNAME(I),1, JADR,JTYP)
 10   CONTINUE
C			     ALL DONE SO DUMP REMAINDER IF ANY
      CALL PUTBLK
      RETURN
      END
      SUBROUTINE OUTOLD
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     OUTPUT AN OLD STYLE DATA BLOCK
C			     IF( IWDCT .LE. 4 ) RETURN
C			     IF( NO DATA TO OUTPUT ) RETURN
C			     SET WORD COUNT
C			     NOTE: ASSUMS 2'S COMPL ARITH
C			     NOW COMPUT THE CHECKSUM
      IF( IWDCT .LE. 3 ) RETURN
      J=-(IWDCT - 3 )
      IBL(1) = IAND(65536+J,65535)
      CALL OUTOLX
      RETURN
      END
      SUBROUTINE OUTOLX
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
      J = 0
      IBL(3)=0
      DO 10 I=1,IWDCT
 10   J = J + IBL(I)
      IBL(3)=IAND(16777216 - J, 65535)
C
C			     NOW WRITE IT OUT
      CALL PNBLK( IBL, IWDCT )
C			     REINITIALIZE THE BUFFER
      CALL STROLD
      RETURN
      END
      SUBROUTINE PNBLK( IBL, IWDCT)
      DIMENSION IBL(10)
      IF( IWDCT .LE. 0 ) RETURN
      DO 10 I=1,IWDCT
   10 CALL PNCH( IBL(I) )
      CALL PNCH( 0 )
      RETURN
      END
      SUBROUTINE PNCH(II)
C
C
      COMMON /PCHB/ J,IBUF(40)
      DATA N /40/
      IF( J .LT. N ) GO TO 20
      CALL FLUSH
   20 CONTINUE
      J = J  + 1
      IBUF(J) = IAND( II , 255 )
      J = J + 1
      IBUF(J) = IAND(IRIGHT(II,8) ,255)
      RETURN
      END
      SUBROUTINE PTAPES
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
      LOGICAL SFLG
C			     MASTER HANDLER FOR PUNCHING PAPER TAPE
C
C
C			     DONT PROCESS IF PASS1
C     RESET THE DATA START FLAG
      IF( PASS1 ) SFLG = .FALSE.
      IF( PASS1 ) RETURN
      IF( .NOT. PTAPE ) RETURN
C			     IF ( IN THE CODE SECTION )
C			     IF( NO DATA TO PROCESS ) RETURN
      IF( NWDS .EQ. 0 ) RETURN
C			     IF( ALREADY STARTED ON THE DATA ) DONT INIT
      IF( SFLG ) GO TO 20
C			     HAVE COME TO THE BEGINING OF THE DATA
      SFLG = .TRUE.
C			     IF( ANY RELOCATABLE COSE)
      IF( RELASM ) GO TO 10
C			     NO RELOCATABLE CODE SO OUTPUT OLD STYLE
      CALL STROLD
      GO TO 20
C			     RELOCATABLE OUTPUT
 10   CONTINUE
      CALL STRBLK(2)
C
 20   CONTINUE
C			     MAKE SURE THERE IS SOME DATA TO OUTPUT
      IF( NWDS .LE. 0 ) GO TO 50
C
C			     NOW OUTPUT THE INDIVIDUAL DATA
      DO 40 I=1,NWDS
C			     IF ( RELOCATABL STYLE )
      IF( RELASM ) GO TO 30
C			     OLD STYLE
      CALL PUTOLD( IWORD(I) , LOCCNT )
      GO TO 40
C			     RELOCATABLE STYLE
 30   CONTINUE
      CALL ADNBLK( IWORD(I), IWTYPE, LOCCNT, IMODE )
C			     BUMP LOCATION COUNTER TO NEXT  LOC
 40   LOCCNT = LOCCNT + 1
      LOCCNT = LOCCNT - NWDS
C
C			     ALL DONE WITH THIS CARD'S DATA
 50   CONTINUE
      RETURN
      END
      SUBROUTINE PTAPET
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
      IF(.NOT.PTAPE) RETURN
C     LEADER
      CALL LEADR(3)
      IF(.NOT.RELASM) RETURN
      CALL STRBLK(7)
      CALL ADSBLK(ITITLE,4,0,0)
      CALL PUTBLK
      RETURN
      END
      SUBROUTINE PUTBLK
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     OUTPUT A BLOCK TO PAPER TAPE IN RELOC STYLE
C			     DON'T BOTHER IF THE WORD COUNT IS .LT.6
      IF( IWDCT .LE. 6 ) RETURN
C			     SET WORD CONT
      J=65536 - (IWDCT - 6)
      IBL(2) = IAND(J,65535)
C
C			     COMPUT CHECKSUM
      J = 0
      DO 10 I=1,IWDCT
 10   J = J + IBL(I)
      IBL(6)=IAND(16777216 - J, 65535)
C
C			     OUTPUT THE BLOCK WITH 2 FRAMES OF BLANKS
      CALL PNBLK( IBL, IWDCT )
      J = IBL(1)
C			     NINITIALIZE A SIMILAR BLK TYPE
      CALL STRBLK( J )
      RETURN
      END
      SUBROUTINE PUTOLD( IV, IAD )
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     PUT 1 WORD INTO THE BUFFER
C			     TAPE IS THE OLD STYLE
C
C			     CHECK THAT ADDRESSES ARE IN SEQUENCE
      IF( IAD .EQ. IADL ) GO TO 10
C			     MUST START A NEW BLOCK SO DUMP THE OLD ONE
C			     NOTE: BLOCK WILL NOT BE DUMPED UNLESS IT
C			     HAS SOME DATA IN IT
      CALL OUTOLD
      IADL = IAD
      IBL(2) = IAD
C
C
 10   CONTINUE
C			     NOW PUT IN THE DATUM
      IWDCT = IWDCT + 1
      IBL(IWDCT) = IAND(IV,65535)
C			     NOW SET IADL FOR NEXT ENTRY
      IADL = IADL + 1
C
C			     CHECK IF BUFFER FULL
      IF( IWDCT .EQ. 19 ) CALL OUTOLD
      RETURN
      END
      SUBROUTINE RADX( IV )
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
      NWDS = 0
      IOCLAS = 4
      IF( SKPFLG ) RETURN
      IOCLAS = 3
      IR = IRADIX
      IRADIX = 10
      CALL EXPRES( I, IT, MO)
      IF( I.GT.10 .OR. I.LT.2 .OR. IT.NE.1 .OR. MO.NE.1) GO TO 50
      IRADIX = I
 10   CONTINUE
      IWORD(1) = IRADIX
      IWTYPE = 1
      RETURN
   50 CONTINUE
      CALL ERROR(1HD)
      I = 8
      GO TO 10
      END
      SUBROUTINE RANGE( IV, MODE)
C
C
      EQUIVALENCE (IX,X)
C
      IX = IV
C			     BRANCH ON SINGLE, DOUBLE OR FLOATING PR
      GO TO ( 10,20,30) , MODE
C			     SINGLE
   10 IF(IV.LT.(-32768) .OR. IV.GT. 65535 ) CALL ERROR(1HN)
      GO TO 40
C			     DOUBLE PRECISION
   20 IF( IV.LT.(-2147483647) .OR. IV.GT.2147483647) CALL ERROR(1HN)
      GO TO 40
C			     FLOATING POINT
C   30 IF( ABS(X).LT.8.7E-78 .OR. ABS(X).GT.7.2E75 ) CALL ERROR(1HN)
   30 CONTINUE
   40  CONTINUE
      RETURN
      END
 >Ø