@677

Master master
This is recorded thru uh flies ear
'n you have t' have uh flies eye t' see it
It's the thing that's gonna make Captain Beefheart
and his magic band fat
Frank it's the big hit
It's the blimp
It's the blimp Frank
It's the blimp

When I see you floatin' down the gutter
I'll give you uh bottle uh wine
Put me on the white hook
Back in the fat rack
Shad rack ee shack
The sumptin' hoop the sumptin' hoop
The blimp the blimp
The drazy hoops the drazy hoops
They're camp they're camp
Tits tits the blimp the blimp
The mother ship the mother ship
The brothers hid under their hood
From the blimp the blimp
Children stop yer nursin' unless yer renderin' fun
The mother ship the mother ship
The mother ship's the one
The blimp the blimp
The tapes uh trip it's uh trailin' tail
It's traipse'n along behind the blimp the blimp
The nose has uh crimp
The nose is limp the blimp
It blows the air the snoot isn't fair
Look up in the sky there's uh dirigible there
The drazy hoops whir
You can see them just as they were
All the people stir
'n the girls knees trembles
'n run 'n wave their hands
'n run their hands over the blimp the blimp
Daughter don't yuh dare
Oh momma who cares
It's the blimp it's the blimp

@0
Undeclared identifier
@1
Error in simple expression
@2
Not the correct matching close bracket
@3
Missing delimiter between expressions
@4
Operator not followed by simple expression
@5
Relational exp. followed by relational operator
@6
Binary operator used as unary or vice versa
@7
Control expression used as subexpression
@10
Illegal assignment left part
@11
More than 8 "_"s
@12
Illegal assignment right part
@13
Empty actual parameter
@14
Simple expression not followed by delimiter
@15
Empty subscript expression
@16
More than 8 subscripts
@17
Null selector in case expression
@20
OF not followed by SET in CASE expression
@21
Illegal escape expression
@22
Missing control variable in INCR or DECR
@23
Empty expression within complex expression
@25
Declaration not in block head
@30
Current close bracket does not match open bracket
@31
Incorrect close bracket
@36
Illegal control variable name in INCR or DECR
@37
Empty condition in WHILE or UNTIL
@40
Reference to local variable declared
outside current routine
@41
Too many parameters in pointer expression
@42
Too many close brackets or not enough opens
@43
Too many close brackets or not enough opens
@44
FROM-TO-BY-DO out of order in INCR or DECR
@45
Empty DO part in INCR or DECR
@46
Empty condition in IF
@47
Missing THEN
@50
Empty FROM, TO, or BY in INCR or DECR
@51
Number of levels in escape expression
not a compile-time constant
@52
Missing "]" in escape expression
@53
Empty pointer-pointer in special function
@54
Missing ")" in special function
@55
Missing OF in SELECT
@56
Missing or misplaced NSET in SELECT
@57
Empty label in nset-element
@60
Missing or misplaced ":" in SELECT
@61
Missing or misplaced TESN in SELECT
@62
Empty elist element in SELECT
@63
SET illegal at beginning of expression
@64
Missing "(" after EXCHJ
@65
Empty new-base expression in EXCHJ
@66
Missing ")" in EXCHJ
@67
Missing AT in CREATE
@70
Missing AT-expression or LENGTH in CREATE
@71
Missing LENGTH-expression or THEN in CREATE
@72
Missing "(" after CREATE
@74
Declared symbol not an identifier
@75
Missing "=" in declaration
@76
Missing formal parameter list right delimiter
@77
Missing "]" after size portion of declaration
@100
Missing "," or ";" in list
@101
Missing ")" in EXTERNAL or FORWARD
@103
Missing "=" in MACHOP
@104
Missing ",", ":", or ";" in allocation declaration
@105
Identifier precedeng a declaration
@106
Structure access not to an identifier
@126
Register is not reserved or 'system' type
@127
Register value out of range
@130
Register value not compile-time constant
@131
Structure access to unmapped variable
@132
Extra incarnation actuals ignored
@133
Block illegal as size expression
@134
Symbol may not be addressed or mapped
@135
Illegal expression in FORWARD
@136
Illegal expression in MACHOP
@137
May not map symbol of this type
@140
Attempt to map onto undeclared structure
@141
Incarnation actual or resulting size
exp. not compile-time constant
@142
Delimiters for balanced string do not match
@143
Symbol previously declared in current block
@144
Illegal attempt to escape from routine or function
@145
use of temporary register may invalidate code
@146
Register in machine op. must be register
name or compile-time constant
@147
Indirect field in machine op. must be constant
@150
Missing ")" in machine language expression
@170
Illegal macro name
@171
Empty formal list in macro definition
@172
More than 31 formals in macro formal list
@173
Illegal formal parameter
@174
Macro definition durin macro expansion illegal
@175
Recursive macro call illegal
@176
Macro in use at block purge time
@177
"(" missing in macro call
@200
Missing exponent in floating constant, 0 assumed
@201
Compile-time division by zero
@400
Missing "(" in special function call
@401
Illegal ELSE in compound expression or block
@402
Missing ";" before OTHERWISE or ALWAYS
@403
HORRENDOUS ERROR: Compiler attempted to
generate machine address for an identifier of illegal type
@404
GLOBAL BIND must be to compile-time constant
@405
More than 15 formals in structure declaration
@406
HORRENDOUS ERROR: Compiler couldn't shrink back to original size
@407
Line longer than 135 characters
@410
Missing name preceding NAMES or INDEXES
@411
Name used in NAMES or INDEXES already declared
@412
NAMES or INDEXES illegal in portion of PLIT
subject to duplication
@413
Identifier declared GLOBAL elsewhere
@414
NAMES or INDEXES missing after GLOBALLY
@415
Too few actual parameters in structure access
@416
Illegal use of label
@417
Atom following LEAVE is not a proper label
@420
Label previously used in this block
@421
Reference to label outside its scope
@422
Parameter to OFFSET not local or formal variable name
@423
This construct is scheduled to be removed from BLISS
at some future date.  Suggest you avoid using the construct.
@500
Input error while reading source file
@601
Improper switch use
@602
Terminating ";" missing in SWITCHES declaration
@603
Illegal switch name
@606
Missing parentheses in RESERVE declaration
@610
Missing "=" after DREGS
@612
Register name not compile-time constant in range 0-15
@613
MODULE declaration within module body
@614
Invalid type in STACK or TIMER declaration
@615
Syntax error in STACK or TIMER declaration
@616
Illegal size expression in STACK or TIMER declaration
@617
Attempt to reserve a register already in use
@620
Illegal special register number
@621
Attempt to declare a special register already in use
@622
MODULE errors, compilation started at pointer
@623
More than 12 reserved+special+declarable registers
@624
Missing "=" in special register declaration
@625
Module declaration errors with a trivial program
@626
Syntax errors in ENTRIES
@627
Declared entry point is not defined
@630
Missing ")" in PLIT
@631
Illegal compile-time expression
@632
Illegal load-time expression
@633
Negative PLIT duplication factor illegal
@634
Long string used in illegal context
@635
String missing right quote
@636
Illegal escape character in string
@637
Extra actuals in structure access
@760
No temporary register available
@761
No declared register available for INCR or DECR
@762
No declared register available for declaration
@770
Ran out of core, compilation aborted
@771
HORRENDOUS ERROR: gt savef overflow
@772
HORRENDOUS ERROR: register table use field overflow
@773
HORRENDOUS ERROR: graph table UCCF overflow
@774
HORRENDOUS ERROR: literal table overflow
@775
HORRENDOUS ERROR: pointer table overflow
@776
Missing delimiter between operands
@777
HORRENDOUS ERROR: mysterious compiler error
  