TITLE CLOZIT - C. NEUSTRUP - APRIL 1, 1973
; CLOSE FILE WITHOUT DEALLOCATING THE SPACE UNUSED

;       CALL BY:        CALL CLOZIT (FILNUM)

        INTERN  CLOZIT
        ENTRY   CLOZIT

        OPDEF   FCALLI [35B8]

CLOZIT: JFCL
        MOVEM   0,SAVE
        MOVE    0,@0(16)        ; GET FILE NUM TO 0
        FCALLI  0,1B33
        MOVE    0,SAVE
        JRA     16,1(16)

SAVE:   BLOCK   1

        END
