.PLEASE % 1(54) Version of FRTCOM.CTL    
; FORTRAN Compiler and Operating System Assembler
; Written by M Manugian/WLH/FMH
; Submit with command .SUB FRTCOM/TIME:2::/UNIQ:0

; Control file assumes all files to be on user's PPN:[31,2112]
; on  the private str for1 and that that STR has two available
; PPN's [31,1],[31,2] for the creation of the save set areas.

; The following files are required for the running  of  FRTCOM
; and  are  in no other way related to the FORTRAN compiler or
; operating system.

;	FRTFIL.SHR	; PROGRAM DETERMINES IF ALL REQUIRED FILES
;			; ARE PRESENT ON THE DSK AREA

;	FRTFIL.CHK	; DATA FILE FOR FRTFIL.SHR

;	FRTFRT.MST	; VERSION LEVEL OF THE DEVELOPERS' VERSION
;			; OF FOROTS.CTL AND FORT?.CTL

;	FRTMON.SHR	; PROGRAM TO QUERY OPERATOR FOR THE RELEASE MONTH

;	FRTREL.CCL	; PIP INDIRECT FILE TO CREATE THE SOURCE FILE
;			; RELEASE AREA [31,1]

;	FRTSAV.CCL	; PIP INDIRECT FILE TO CREATE THE CUSP FILE
;			; AREA [31,2]

;	WAIT.SHR	; HACK PROGRAM TO WAIT FOR FOROTS.CTL TO CREATE
;			; FOROTS.SHR


; BLIS10 SWITCH SUMMARY
;	/M	MACRO CODE
;	/S	MONITOR COMPILATION
;	/G	GLOBAL ROUTINES
;	/K	INHIBIT LISTING
;	/L	MAKE LISTING


;	FMH, 23-APRIL-73:
;		ALL COMPILER BLIS10-COMPILATIONS MODIFIED TO ALSO
;		PRODUCE MACRO-LISTING OUTPUT (.MAC)

.SET WATCH VERSION,RUN

MT::.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO MA
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO MT

MA::.MOUNT BLKE/VID:'FORTRAN COMPILER CONTROL FILE'
.IF (NOERROR) .GOTO MTOP
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO MA

MTOP:: ; GET A DIRECTORY OF THE FOROTS AREA ON BLKE
.DIR/CHECKSUM BLKE:[7,6372]
; GET ALL THE FOROTS FILES ONTO OUR DSK AREA
.COPY DSK:=BLKE:[7,6372]*.*
.COPY DSK:=BLKE:[7,6370]BAKWDS.*
.DISMOUNT BLKE/VID:'FORTRAN COMPILER CONTROL FILE'/REMOVE
.IF (ERROR)	; OK
; GET ALL THE BLIS10 SOURCES FROM BLKB:[7,6242]
.GOTO ZERPP
MTB::.MOUNT BLKB/VID:'FRTCOM - BLIS10 SOURCES'
.IF (NOERROR) .GOTO PKMON
.PLEASE FRTCOM - OPERATOR MOUNT THE PACK AND CONT OR KILL THIS JOB
.BACKTO MTB

PKMON::.RUN PIP[10,7]
*FOR1:(XB)_BLKB:[7,6242]*.*

.DISMOUNT BLKB/REMOVE
.IF (ERROR)	; OK

; NOW GET A COPY OF QERROR.FRM FROM SYS
.COPY DSK:=SYS:QERROR.FRM

; Now make sure all necessary files  are  available.
; The   program   FRTFIL.SHR  reads  the  data  file
; FRTFIL.CHK which  is  a  list  of  all  the  files
; required   for  the  successful  running  of  this
; control file.

TPTST:: ; NOW RUN FRTFIL TO MAKE SURE WE HAVE ALL THE SOURCE FILES
;         REQUIRED FOR BLIS10,FORTRAN,FOROTS

.OPERATOR %
.RUN DSK:FRTFIL
.NOOPERATOR

; NOW COMPARE FOROTS.CTL,BLIS10.CTL & FORT?.CTL FILES TO A MASTER TO DETERMINE
; IF DEVELOPERS HAVE ADDED ANY BELLS AND WHISTLES TO THEIR CONTROL FILES.

SCDTS::.DIRECT FRTFRT=/CHECKSUM FOROTS.CTL,FORT?.CTL,BLIS10.CTL

; The program SCDCP compares directory files and
; outputs the differences encountered
.R SCDCP
*FRTFRT.DIR,FRTFRT.MST

.GOTO ZERPP
STBL::
.MOUNT FOR1
; START OF BLIS10 COMPILATION SEQUENCE
.TYPE BLIS10.PIP
.RUN PIP[10,7]
*BLIS10.PIP@
;
; NOW DO THE COMPILATIONS
LOK:: .CHKPNT LOK
.RUN DSK:BLIS10
*/SLOBLI_START0,BEGIN,LOBLI,END.B10
;
H1K:: .CHKPNT H1K
.RUN DSK:BLIS10
*/SH1BLI_START1,BEGIN,H1BLI,END.B10
;
H2K:: .CHKPNT H2K
.RUN DSK:BLIS10
*/SH2BLI_START2,BEGIN,H2BLI,END.B10
;
H3K:: .CHKPNT H3K
.RUN DSK:BLIS10
*/SH3BLI_START3,BEGIN,H3BLI,END.B10
;
; NOW COMPILE THE MACRO-10 SOURCES.
;
.RUN MACRO[10,7]
*XJBDAT_XJBDAT
.RUN MACRO[10,7]
*LOIO_LOIO
.RUN MACRO[10,7]
*LOONCE_LOONCE
;
;
; NOW LOAD THE COMPILER
.RUN DSK:LOADER[10,7]
.TYPE BLIS10.LDR
.RUN LOADER[10,7]
*BLIS10.LDR@
.SSAV BLIS10
;
;
; NOW DELETE UNNECESSARY FILES.
.DELETE LOBLI.BLI,H1BLI.BLI,H2BLI.BLI,H3BLI.BLI
; THIS IS THE END OF THE BLIS10 COMPILATION SEQUENCE
; NOW MAKE SURE FOR1:[31,1] & [31,2] ARE EMPTY
; IF THEY ARE NOT WE MUST REQUEST THE OPERATOR TO ZERO
; THEM AND CONTINUE 

ZERPP::.CHKPNT ZERPP
.MAKE DUMMY.DIR
*I% EMPTY DIRECTORY
*EX
.DIRECT /CHECKSUM DUMMY.CMP=FOR1:[31,1],FOR1:[31,2]
.R SCDCP
*DUMMY.OUT=DUMMY.CMP,DUMMY.DIR/N
.IF (NOERROR) .GOTO OKPPD

ERPPD::.PLEASE FRTCOM - OPER PLEASE ZERO FOR1:[31,1] & [31,2] AND CONTINUE
.BACKTO ZERPP

OKPPD::.DELETE DUMMY.*
.IF (ERROR)	; OK
; HERE TO COMPILE FOROTS (KA10)

FT001::.CHKPNT FT001
.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO FT002
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO FT001

FT002:: ; LET'S WATCH VERSIONS AND RUNTIME
.SET WATCH VERSION,RUN
;
.NOERROR
.PROTECT <100> FOROTS.SHR,FOROTS.LOG,FOR?K?.*
.DELETE FOROTS.SHR,FOROTS.LOG,FOR?K?.*,*.REL,*.BAK,*.LST,*.CRF
.ERROR
;
; FIRST PRODUCE THE KA10 VERSIONS OF FOROTS.SHR & FORLIB.LIB

KA10::.CHKPNT KA10
.TECO FORPRM.MAC
*N<CPU==K102R-DIAEX
.PLEASE FRTCOM - SUBMITTING FOROTS.CTL (KA10 VERSION)
.SUBMIT FOROTS/REST:1/TIME:10:0/UNIQ:0
;
; NOW WAIT FOR THE OPERATOR TO TELL US THAT FOROTS IS DONE
.PLEASE FRTCOM - WAIT FOR FOROTS.CTL TO FINISH BEFORE PROCEEDING

; NOW RENAME TO KA10 FUNNIES
.RENAME FORLKA.REL=FORLIB.LIB
.RENAME FOROKA.SHR=FOROTS.SHR


.GOTO FT003

%CERR:
%ERR:.PLEASE FRTCOM - ERROR IN PRODUCING KA10 FOROTS  
.GOTO END

FT003::
; HERE TO COMPILE FOROTS (KI10)

FA001::.CHKPNT FA001
.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO FA002
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO FA001

FA002:: ; LET'S WATCH VERSIONS AND RUNTIME
.SET WATCH VERSION,RUN
;
.DELETE FOROTS.LOG
;
KA10::.CHKPNT KA10
.TECO FORPRM.MAC
*N<CPU==K102R-DIIEX
.PLEASE FRTCOM - SUBMITTING FOROTS.CTL (KI10 VERSION)
.SUBMIT FOROTS/REST:1/TIME:10:0/UNIQ:0
;
; NOW WAIT FOR THE OPERATOR TO TELL US THAT FOROTS IS DONE
.PLEASE FRTCOM - WAIT FOR FOROTS.CTL TO FINISH BEFORE PROCEEDING

; NOW RENAME TO KI10 FUNNIES
.RENAME FORLKI.REL=FORLIB.LIB
.RENAME FOROKI.SHR=FOROTS.SHR


.GOTO FA003

%CERR:
%ERR:.PLEASE FRTCOM - ERROR IN PRODUCING KI10 FOROTS  
.GOTO END

FA003::
; ********** FORTA.CTL **********
; NAME:		FORTRAN.CTL
; DATE:		9 JAN 73
;
; FUNCTION:	THIS CONTROL FILE BUILDS THE STANDARD FORTRAN COMPILER
;		FROM ITS BASIC SOURCES.  IT UTILIZES DSKB:[10,7] FOR
;		FIELD IMAGE SOFTWARE AS REQUIRED BY -10 QA; BUT CAN
;		UTILIZE A STANDARD SYS BY MAKING THE MODIFICATION NOTED
;		BELOW IN THE AREA SET OFF BY LINES OF ASTERISKS.
;
; INPUT:		THE FOLLOWING FILES ARE REQUIRED BY THIS JOB IN THE
;		DISK AREAS INDICATED:
;
;	DSKB:[10,7]
;		DIRECT.SHR
;		JOBDAT.REL
;		LOADER.SHR
;		MACRO.SHR
;		COMPIL.SHR
;
;	DSK:[AREA UNDER WHICH FORTRAN.CTL IS BEING RUN]
;
;		INDIRECT COMMAND FILES USED BY FORTRAN.CTL:
;		IO.CMD		LOADS I/O UTILITIES FOR SYNTAX TABLE BUILDERS
;		P0.CMD		LOADS FORTRA
;		P1.CMD		LOADS FORTB
;		P2S.CMD		LOADS FORTC
;		P2.CMD		LOADS FORTD
;		P3R.CMD		LOADS FORTE
;		P3G.CMD		LOADS FORTF
;		P3.CMD		LOADS FORTG
;
;		SOURCES FOR BUILDING SYNTAX TABLES:
;		BLIO.BLI
;		BUILD.BLI
;		DEFLT.BLI
;		ERROR0.BLI
;		ERRTB3.MAC
;		F72BNF.SYN
;		FORMAT.SYN
;		LEFT.BLI
;		LHEAD.BLI
;		NUMIO1.BLI
;		OUTZ.BLI
;		QTAB1.MAC
;		SCAN0.BLI
;		SCNR.BLI
;		SYNTAB.BLI
;		SYNTAX.BLI
;		SYNTHD.BLI
;		TBL.BLI
;		TRACE1.BLI
;
;		REMAINING COMPILER SOURCES:
;
; OUTPUT:	THE FOLLOWING FILES ARE GENERATED BY THIS CONTROL JOB
;		AND WILL BE AVAILABLE ON THIS DISK AREA AT JOB TERMINATION.
;
;	DSK:[AREA UNDER WHICH FORTRAN.CTL IS BEING RUN]
;
;		FROM SYNTAX TABLE BUILDING SECTION:
;		*	INDICATES REQUIRED FORTRAN COMPILER SOURCE COMPONENT
;		ALL.SYN
;		BLIO.REL
;		BUILD.HGH
;		BUILD.LOW
;		BUILD.LST
;		BUILD.REL
;		DEFLT.REL
;		ERROR0.REL
;		ERRTB3.REL
;		F72.BLI
;	       *F72BNF.BLI
;	       *FORMAT.BLI
;		LEFT72.LST
;		LEFT72.REL
;		LEFTFM.LST
;		LEFTFM.REL
;	       *LOOK72.BLI
;	       *LOOKFM.BLI
;		M72.BLI
;	       *META72.BLI
;		METAFM.BLI
;		NUMIO1.REL
;		OUTZ.REL
;		QTAB1.REL
;		SCAN0.REL
;		SCNR.REL
;		SNTAB.HGH
;		SYNTAB.LOW
;		TBL.REL
;		TRACE1.REL
;
;
;
;

P0BEG::.PLEASE FRTCOM - ENTERING THE PHASE 0 BUILDING SECTION   

PT::.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO PA
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO PT

PA::.SET TTY NOBLANKS
.IF (ERROR)

;
;
; FIRST WE BUILD THE SYNTAX TABLE BUILDERS AND SYNTAX TABLES
;
.PLEASE FRTCOM - COMPILING THE SYNTAX TABLE BUILDER
; FIRST COMPILE AND LOAD THE TABLE BUILDING PROGRAM.
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*BUILD/C/S,BUILD.MAC/M_BUILD
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING BUILD
;
;
;
; NOW COMPILE ALL I/O UTILITIES.
;
;
.RUN DSK:MACRO[10,7]
*QTAB1_QTAB1
.IF (ERROR) .PLEASE FRTCOM - ERROR IN ASSEMBLING QTAB1
;
;
;
.RUN DSK:MACRO[10,7]
*ERRTB3_ERRTB3
.IF (ERROR) .PLEASE FRTCOM - ERROR IN ASSEMBLING ERRTB3
;
;
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*SCAN0,SCAN0.MAC/M_SCAN0
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING SCAN0
;
;
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*SCNR,SCNR.MAC/M_SCNR
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING SCNR
;
;
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*TRACE1,TRACE1.MAC/M_TRACE1
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING TRACE1
;
;
;
.RUN DSK:BLIS10
*ERROR0,ERROR0.MAC/M_ERROR0
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING ERROR0
;
;
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*BLIO,BLIO.MAC/M_BLIO
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING BLIO
;
;
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*NUMIO1,NUMIO1.MAC/M_NUMIO1
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING NUMIO1
;
;
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*DEFLT,DEFLT.MAC/M_DEFLT
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING DEFLT
;
;
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*TBL,TBL.MAC/M_TBL
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING TBL
;
;
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*OUTZ,OUTZ.MAC/M_OUTZ
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING OUTZ
;
;
;
; NOW LOAD THE BUILDER WITH I/O UTILITIES AND EXECUTE
.TYPE IO.CMD
.LOAD @IO,BUILD
.IF (NOERROR) .GOTO OK1
.PLEASE FRTCOM - ERROR IN LOADING @IO OR BUILD
.GOTO BD1
OK1::.SAVE BUILD
BD1::.IF (ERROR) .PLEASE FRTCOM - ERROR IN SAVING BUILD
;
;
;
; NOW BUILD THE SYNTAX TABLES
; FIRST BUILD TABLES FOR SYNTAB
.NOERROR
.RUN DSK:BUILD
*M72.BLI,F72.BLI_F72BNF.SYN
*0
*Y
; NEXT
.RUN DSK:BUILD
*META72.BLI,F72BNF.BLI_F72BNF.SYN
*0
*N
; NOW BUILD THE NEXT PAIR OF TABLES
.RUN DSK:BUILD
*METAFM.BLI,FORMAT.BLI_FORMAT.SYN
*0
*N
;
;
.ERROR

; NOW DO THE COMPILATIONS FOR THE LOOK AHEAD TABLE BUILDERS.
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*LEFT72/C/S,LEFT72.MAC/M_LHEAD,F72BNF,LEFT
*LEFTFM/C/S,LEFTFM.MAC/M_SYNTAX,FORMAT,LEFT
;
;
;
; NOW LOAD, SAVE, AND EXECUTE THE GENERAL SYNTAX LOOK AHEAD BUILDER
.LOAD @IO,LEFT72
.IF (ERROR)	; OK
OK2::.SAVE LEFT72
BD2::.NOERROR
.RUN DSK:LEFT72
*3=LOOK72.BLI
*0
;
;
.ERROR
; NOW LOAD, SAVE, AND EXECUTE THE FORMAT LOOK AHEAD TABLE BUILDER
.LOAD @IO,LEFTFM
.IF (ERROR)	; OK
OK3::.SAVE LEFTFM
BD3::.NOERROR
.RUN LEFTFM
*3=LOOKFM.BLI
*0
.ERROR
;
;
; NOW LOAD AND SAVE SYNTAB AND GENERATE AN EXPANSION OF ALL
; METASYMBOL DEFINITIONS.
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*SYNTAB/C/S,SYNTAB.MAC/M_SYNTHD,M72,F72,SYNTAB
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING SYNTHD,M72,F72,SYNTAB
;
;
;
.LOAD @IO,SYNTAB
.IF (ERROR)	; OK
OK4::.SAVE SYNTAB
BD4::.NOERROR
.RUN DSK:SYNTAB
*ALL.SYN
=
*
*
;
.ERROR
;
;
;000000000000000000000000000000000000000000000000000000000000
; NOW LET'S COMPILE AND LOAD PHASE 0.
;
;
;
PATCK:: .CHKPNT PATCK
Q0::.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO R0
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO Q0

R0::.PLEASE FRTCOM - COMPILE AND LOAD PHASE 0
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*PATCH/S/G,PATCH.MAC/M_PATCH.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING PATCH.BLI
;
;
;
.SET TTY NOBLANKS
MAINCK:: .RUN DSK:BLIS10
*MAIN/S/G,MAIN.MAC/M_MAIN.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING MAIN.BLI
;
;
;
.SET TTY NOBLANKS
GLOBCK:: .RUN DSK:BLIS10
*GLOBAL/S/G,GLOBAL.MAC/M_GLOBHD,FIRST,TABLES,GLOBAL
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING GLOBHD,TABLES,GLOBAL
;
;
;
.SET TTY NOBLANKS
SRCACK:: .RUN DSK:BLIS10
*SRCA/S/G,SRCA.MAC/M_SRCAHD,FIRST,TABLES,SRCA,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING SRCAHD,FIRST,TABLES,SRCA,END
;
;
;
.SET TTY NOBLANKS
INOUCK:: .RUN DSK:BLIS10
*INOUT/S/G,INOUT.MAC/M_INOUT.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING INOUT.BLI
;
;
;
.SET TTY NOBLANKS
ERROCK:: .RUN DSK:BLIS10
*ERROUT/S/G,ERROUT.MAC/M_ERROUT.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING ERROUT.BLI
;
;
;
.SET TTY NOBLANKS
STATCK:: .RUN DSK:BLIS10
*STATOU/S/G,STATOU.MAC/M_STATOU.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING STATOU.BLI
;
;
;
ERR3CK:: .RUN DSK:MACRO[10,7]
*ERR3_ERR3
.IF (ERROR) .PLEASE FRTCOM - ERROR IN ASSEMBLING ERR3.MAC
;
;
;
.SET TTY NOBLANKS
SRCBCK:: .RUN DSK:BLIS10
*SRCB/S/G,SRCB.MAC/M_SRCBHD,FIRST,TABLES,SRCB,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING SRCBHD,FIRST,TABLES,SRCB,END
;
;
;
;SCNCK::.DIRECT /CHECKSUM SCANHD,C,SCNMAC,SCAN
; .COMPILE /COMPILE SCANHD+<C,SCNMAC,SCAN>

; THE FOLLOWING REPLACES THE ABOVE COMPILE CLASS COMMAND
;.RUN DSK:MACRO[10,7]
;*C_SCANHD,C
;*SCNMAC_SCANHD,SCNMAC
;*SCAN_SCANHD,SCAN
;
;.IF (ERROR) .PLEASE FRTCOM - ERROR IN ASSEMBLING SCAN
;WILDCK:: .RUN DSK:MACRO[10,7]
;.IF (ERROR) .PLEASE FRTCOM - ERROR IN ASSEMBLING C,SCNMAC,WILD
;*WILD_C,SCNMAC,WILD
;
;
;
COMMCK:: .RUN DSK:MACRO[10,7]
*JOBD_JOBD
*SCANDB_SCANDB
*COMMAN_C,SCNMAC,COMMAN
.IF (ERROR) .PLEASE FRTCOM - ERROR IN ASSEMBLING C,SCNMAC,COMMAN
;
;
;
; ALL PHASE 0 SOURCES ARE NOW COMPILED.  LET'S LOAD PHASE 0.
P0CK::.TYPE P0.CMD
.IF (ERROR)
.RUN DSK:LOADER[10,7]
*P0.CMD@
.SSAVE FORTRA
.PLEASE FRTCOM - PHASE 0 BUILDING SUCCESSFUL   
.GOTO P0END

%ERR:
%CERR:.PLEASE FRTCOM - ERROR IN PHASE 0 BUILDING SECTION   
.GOTO END
;
;
;
P0END:
; THIS IS THE END OF PHASE 0 BUILDING SECTION.
;000000000000000000000000000000000000000000000000000000000000
; ********** FORTB.CTL **********

.SET WATCH VERSION,RUN
;111111111111111111111111111111111111111111111111111111111111
; NOW LET'S COMPILE AND LOAD PHASE 1.
;
;
P1BEG::.PLEASE FRTCOM - ENTERING PHASE 1 FORTRAN COMPILE   
;
FLTGK:: .CHKPNT FLTGK
Q1::.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO R1
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO Q1

R1::.PLEASE FRTCOM - COMPILE AND LOAD PHASE 1 (FLTGK)
.RUN DSK:MACRO[10,7]
*FLTGEN_FLTGEN
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING FLTGEN
;
;
;
.SET TTY NOBLANKS
VLTPCK:: .RUN DSK:BLIS10
*VLTPPR/S/G,VLTPPR.MAC/M_VLTPHD,FIRST,TABLES,VLTPPR,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING VLTPHD,FIRST,TABLES,VLTPPR,END
;
;
;
.SET TTY NOBLANKS
ARRXCK:: .RUN DSK:BLIS10
*ARRXPN/S/G,ARRXPN.MAC/M_ARRXHD,FIRST,TABLES,ARRXPN,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING ARRXHD,FIRST,TABLES,ARRXPN,END
;
;
;
.SET TTY NOBLANKS
MAKECK:: .RUN DSK:BLIS10
*MAKEPR/S/G,MAKEPR.MAC/M_MAKEHD,FIRST,TABLES,MAKEPR,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING MAKEHD,FIRST,TABLES,MAKEPR,END
;
;
;
.SET TTY NOBLANKS
DOXPCK:: .RUN DSK:BLIS10
*DOXPN/S/G,DOXPN.MAC/M_DOXPHD,FIRST,TABLES,DOXPN,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING DOXPHD,FIRST,TABLES,DOXPN,END
;
;
;
CNSTCK:: .RUN DSK:MACRO[10,7]
*CNSTCM_CNSTCM
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING CNSTCM
;
;
;
DPSICK:: .RUN DSK:MACRO[10,7]
*DPSIM_DPSIM
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING DPSIM
;
;
;
.SET TTY NOBLANKS
FAZ1CK:: .RUN DSK:BLIS10
*FAZ1/S,FAZ1.MAC/M_FAZ1HD,F72BNF,LOOK72,FIRST,FAZ1,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING FAZ1HD,F72BNF,LOOK72,FIRST,FAZ1,END
;
;
;
.SET TTY NOBLANKS
GNRCCK:: .RUN DSK:BLIS10
*GNRCFN/S,GNRCFN.MAC/M_GNRCHD,FIRST,TABLES,GNRCFN
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING GNRCHD,FIRST,TABLES,GNRCFN
;
;
;
.SET TTY NOBLANKS
EXPRCK:: .RUN DSK:BLIS10
*EXPRES/S/G,EXPRES.MAC/M_EXPRHD,FIRST,TABLES,EXPRES,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING EXPRHD,FIRST,TABLES,EXPRES,END
;
;
;
.SET TTY NOBLANKS
FORMCK:: .RUN DSK:BLIS10
*FORMAT/S,FORMAT.MAC/M_FORMHD,FORMAT,LOOKFM,FMBODY,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING FORMHD,FORMAT,LOOKFM,FMBODY,END
;
;
;
.SET TTY NOBLANKS
ACT0CK:: .RUN DSK:BLIS10
*ACT0/S,ACT0.MAC/M_ACT0HD,FIRST,TABLES,META72,ACT0,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING ACT0HD,FIRST,TABLES,META72,ACT0,END
;
;
;
.SET TTY NOBLANKS
ACT1CK:: .RUN DSK:BLIS10
*ACT1/S,ACT1.MAC/M_ACT1HD,FIRST,TABLES,META72,ACT1,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING ACT1HD,FIRST,TABLES,META72,ACT1,END
;
;
;
STA0CK::.RUN DSK:BLIS10
*/S/GSTA0,STA0.MAC/M_STA0HD,FIRST,TABLES,META72,STA0,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING STA0HD,FIRST,TABLES,META72,STA0,END
;
;
;
.SET TTY NOBLANKS
STA1CK:: .RUN DSK:BLIS10
*STA1/S/G,STA1.MAC/M_STA1HD,FIRST,TABLES,META72,STA1,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING STA1HD,FIRST,TABLES,META72,STA1,END
;
;
;
.SET TTY NOBLANKS
STA2CK:: .RUN DSK:BLIS10
*STA2/S/G,STA2.MAC/M_STA2HD,FIRST,TABLES,META72,STA2,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING STA2HD,FIRST,TABLES,META72,STA2,END
;
;
;
.SET TTY NOBLANKS
STA3CK:: .RUN DSK:BLIS10
*STA3/S,STA3.MAC/M_STA3HD,FIRST,TABLES,META72,STA3,END.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING STA3HD,FIRST,TABLES,META72,STA3,END
;
;
;
.SET TTY NOBLANKS
CLASCK:: .RUN DSK:BLIS10
*CLASS/S,CLASS.MAC/M_CLASHD,FIRST,CLASS.BLI
.IF (ERROR) .PLEASE FRTCOM - ERROR IN COMPILING CLASHD,FIRST,CLASS.BLI
;
;
;
; ALL PHASE 1 SOURCES ARE NOW COMPILED.  LET'S LOAD PHASE 1.
P1CK:: .PLEASE FRTCOM - LOADING PHASE 1 (P1CK)
.TYPE P1.CMD
.IF (ERROR)
.RUN DSK:LOADER[10,7]
*P1.CMD@
.SSAVE FORTB
.PLEASE FRTCOM - PHASE 1 FORTRAN COMPILE SUCCESSFUL   
.GOTO P1END

%ERR:
%CERR:.PLEASE FRTCOM ERROR IN PHASE 1 FORTRAN COMPILE  
.GOTO END
;
;
P1END:
;
; THIS IS THE END OF PHASE 1 BUILDING SECTIO111111111111111111111111111111111111111111111111111111111111
; ********** FORTC.CTL **********
;2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S
; NOW LET'S COMPILE AND LOAD PHASE 2S.
;
;
P2S01:.PLEASE FRTCOM - ENTERING PHASE 2S FORTRAN COMPILE   
;
Q2::.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO R0
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO Q2

R0::.PLEASE FRTCOM - COMPILE AND LOAD PHASE 2S (MEMCP)
MEMCK:: .CHKPNT MEMCK
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*MEMCMP/S,MEMCMP.MAC/M_MEMCHD,FIRST,TABLES,MEMCMP
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING MEMCHD,FIRST,TABLES,MEMCMP
;
;
;
.SET TTY NOBLANKS
SKSTCK:: .RUN DSK:BLIS10
*SKSTMN/S/G,SKSTMN.MAC/M_SKSTHD,FIRST,TABLES,SKSTMN,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING SKSTHD,FIRST,TABLES,SKSTMN,END
;
;
;
.SET TTY NOBLANKS
P2S1CK:: .RUN DSK:BLIS10
*P2S1/S/G,P2S1.MAC/M_P2S1HD,FIRST,TABLES,P2S1,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING P2S1HD,FIRST,TABLES,P2S1,END
;
;
;
.SET TTY NOBLANKS
P2S2CK:: .RUN DSK:BLIS10
*P2S2/S/G,P2S2.MAC/M_P2S2HD,FIRST,TABLES,P2S2,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING P2S2HD,FIRST,TABLES,P2S2,END
;
;
;
.SET TTY NOBLANKS
CANNCK:: .RUN DSK:BLIS10
*CANNON/S/G,CANNON.MAC/M_CANNHD,FIRST,TABLES,OPTMAC,CANNON,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING CANNHD,FIRST,TABLES,OPTMAC,CANNON,END
;
;
;
.SET TTY NOBLANKS
COMSCK:: .RUN DSK:BLIS10
*COMSUB/S/G,COMSUB.MAC/M_COMSHD,FIRST,TABLES,OPTMAC,COMSUB,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING COMSHD,FIRST,TABLES,OPTMAC,COMSUB,END
;
;
;
.SET TTY NOBLANKS
GOPTCK:: .RUN DSK:BLIS10
*GOPTIM/S/G,GOPTIM.MAC/M_GOPTHD,FIRST,TABLES,OPTMAC,GOPTIM,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING GOPTHD,FIRST,TABLES,OPTMAC,GOPTIM,END
;
;
;
.SET TTY NOBLANKS
UTILCK:: .RUN DSK:BLIS10
*UTIL/S/G,UTIL.MAC/M_UTILHD,FIRST,TABLES,UTIL
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING UTILHD,FIRST,TABLES,UTIL
;
;
;
.SET TTY NOBLANKS
PH2SCK:: .RUN DSK:BLIS10
*PH2S/S/G,PH2S.MAC/M_PH2SHD,FIRST,TABLES,PH2S,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING PH2SHD,FIRST,TABLES,PH2S,END
;
;
;
; ALL PHASE 2S SOURCES ARE NOW COMPILED.  LET'S LOAD PHASE 2S.
P2SCK::.TYPE P2S.CMD
.RUN DSK:LOADER[10,7]
*P2S.CMD@
.SSAVE FORTC
.PLEASE FRTCOM - PHASE 2S FORTRAN COMPILE SUCCESSFUL    
.GOTO P2SND

%ERR:
%CERR:.PLEASE FRTCOM - ERROR IN PHASE 2S BUILDING   
.GOTO END
;
;
P2SND:
;
; THIS IS THE END OF PHASE 2S BUILDING SECTION.
;2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S2S
; ********** FORTD.CTL **********


;222222222222222222222222222222222222222222222222222222222222
; NOW LET'S COMPILE AND LOAD PHASE 2.
;
;
P2BEG::.PLEASE FRTCOM - ENTERING PHASE 2 FORTRAN COMPILE 
;
GRAPCK::

Q3::.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO R0
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO Q3

.SET TTY NOBLANKS
R0::.RUN DSK:BLIS10
*GRAPH/S_GRAPHD,OPTMAC,FIRST,TABLES,GRAPH,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING GRAPHD,OPTMAC,FIRST,TABLES,GRAPH,END
;
;
;
.SET TTY NOBLANKS
EFPCK:: .RUN DSK:BLIS10
*DEFPT/S_DEFPHD,FIRST,TABLES,OPTMAC,DEFPT,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING DEFPHD,FIRST,TABLES,OPTMAC,DEFPT,END
;
;
;
.SET TTY NOBLANKS
PNROCK:: .RUN DSK:BLIS10
*PNROPT/S_PNROHD,FIRST,TABLES,OPTMAC,PNROPT,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING PNROHD,FIRST,TABLES,OPTMAC,PNROPT,END
;
;
;
.SET TTY NOBLANKS
PHA2CK:: .RUN DSK:BLIS10
*PHA2/S_PHA2HD,FIRST,TABLES,PHA2,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING PHA2HD,FIRST,TABLES,OPTMAC,PHA2,END
;
;
;
; ALL PHASE 2 SOURCES ARE NOW COMPILED.  LET'S LOAD PHASE 2.
P2CK::.TYPE P2.CMD
.RUN DSK:LOADER[10,7]
*P2.CMD@
.SSAV FORTD
.PLEASE FRTCOM - PHASE 2 FORTRAN COMPILE SUCCESSFUL    
.GOTO P2END

%ERR:
%CERR:.PLEASE FRTCOM - ERROR IN PHASE 2 FORTRAN BUILDING  
.GOTO END
;
P2END:
;
;
; THIS IS THE END OF PHASE 2 BUILDING SECTION.
;222222222222222222222222222222222222222222222222222222222222
; ********** FORTF.CTL **********


;3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R
; NOW LET'S COMPILE AND LOAD PHASE 3R.
;
;
P3RBG::.PLEASE FRTCOM - ENTERING PHASE 3R BUILDING SECTION  
;
STREK:: .CHKPNT STREK
Q4::.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO R0
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO Q4

R0::.PLEASE FRTCOM - COMPILE AND LOAD PHASE 3R (STREK)
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*STREGA/S,STREGA.MAC/M_STREHD,FIRST,TABLES,STREGA,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING STREHD,FIRST,TABLES,STREGA,END
;
;
;
.SET TTY NOBLANKS
CMPLCK::.RUN DSK:BLIS10
*CMPLEX/S,CMPLEX.MAC/M_CMPLHD,FIRST,TABLES,CMPLEX,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING CMPLHD,FIRST,TABLES,CMPLEX,END
;
;
;
.SET TTY NOBLANKS
DOALCK:: .RUN DSK:BLIS10
*DOALC/S,DOALC.MAC/M_DOALHD,FIRST,TABLES,DOALC,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING DOALHD,FIRST,TABLES,DOALC,END
;
;
;
.SET TTY NOBLANKS
REGACK:: .RUN DSK:BLIS10
*REGAL2/S,REGAL2.MAC/M_REGAHD,FIRST,TABLES,REGAL2,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING REGAHD,FIRST,TABLES,REGAL2,END
;
;
;
.SET TTY NOBLANKS
OUTMCK:: .RUN DSK:BLIS10
*OUTMOD/S,OUTMOD.MAC/M_OUTMHD,FIRST,TABLES,OUTMOD,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING OUTMHD,FIRST,TABLES,OUTMOD,END
;
;
;
.SET TTY NOBLANKS
LISTCK:: .RUN DSK:BLIS10
*LISTOU/S,LISTOU.MAC/M_LISTHD,FIRST,TABLES,LISTOU,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING LISTHD,FIRST,TABLES,LISTOU,END
;
;
;
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*DATAST/S,DATAST.MAC/M_DATAHD,FIRST,TABLES,DATAST
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING DATAHD,FIRST,TABLES,DATAST
;
;
;
.SET TTY NOBLANKS
PH3RCK:: .RUN DSK:BLIS10
*P3R/S,P3R.MAC/M_P3RHD,FIRST,TABLES,P3R,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING P3RHD,FIRST,TABLES,P3R,END
;
;
;
; ALL PHASE 3R SOURCES ARE NOW COMPILED.  LET'S LOAD PHASE 3R.
P3RCK::.TYPE P3R.CMD
.RUN DSK:LOADER[10,7]
*P3R.CMD@
.SSAVE FORTF
.PLEASE FRTCOM - PHASE 3R FORTRAN COMPILE SUCCESSFUL   
.GOTO P3RND

%ERR:
%CERR:.PLEASE FRTCOM - ERROR IN PHASE 3R BUILDING SECTION  
.GOTO END
;
;
P3RND:
;
; THIS IS THE END OF THE PHASE 3R BUILDING SECTION.
;3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R3R
; ********** FORTE.CTL **********


;3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G
; NOW LET'S COMPILE AND LOAD PHASE 3G.
;
P3GBG::.PLEASE FRTCOM - ENTERING PHASE 3G FORTRAN COMPILE  
;
;
PH3GK:: .CHKPNT PH3GK
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*PH3G/S_PH3GHD,FIRST,TABLES,OPTMAC,PH3G,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING PH3GHD,FIRST,TABLES,OPTMAC,PH3G,END
;
;
;
; ALL PHASE 3G SOURCES ARE NOW COMPILED.  LET'S LOAD PHASE 3G.
P3GCK:: .CHKPNT P3GCK
.TYPE P3G.CMD
.RUN DSK:LOADER[10,7]
*P3G.CMD@
.SSAVE FORTE
.PLEASE FRTCOM - PHASE 3G  FORTRAN COMPILE SUCCESSFUL   
.GOTO P3GND

%ERR:
%CERR:.PLEASE FRTCOM - ERROR IN PHASE 3G FORTRAN COMPILE   
.GOTO END
;
;
P3GND:
;
; THIS IS THE END OF THE PHASE 3G BUILDING SECTION.
;3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G3G
; ********** FORTG.CTL **********


;333333333333333333333333333333333333333333333333333333333333
; NOW LET'S COMPILE AND LOAD PHASE 3.
;
P3BEG::.PLEASE FRTCOM - ENTERING PHASE 3 FORTRAN COMPILE   
;
;
OPTCK:: .CHKPNT OPTCK
Q5::.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO R0
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO Q5

R0::.PLEASE FRTCOM - COMPILE AND LOAD PHASE 3 (OPTCK)
.SET TTY NOBLANKS
.RUN DSK:BLIS10
*OPTAB/S,OPTAB.MAC/M_OPTAHD,OPTAB
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING OPTAHD,OPTAB
;
;
;
.SET TTY NOBLANKS
CGDOCK:: .RUN DSK:BLIS10
*CGDO/S,CGDO.MAC/M_CGDOHD,FIRST,TABLES,CGDO,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING CGDOHD,FIRST,TABLES,CGDO,END
;
;
;
.SET TTY NOBLANKS
CGSTCK:: .RUN DSK:BLIS10
*CGSTMN/S,CGSTMN.MAC/M_CGSTHD,FIRST,TABLES,CGSTMN,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING CGSTHD,FIRST,TABLES,CGSTMN,END
;
;
;
.SET TTY NOBLANKS
GEXCK:: .RUN DSK:BLIS10
*CGEXPR/S,CGEXPR.MAC/M_CGEXHD,FIRST,TABLES,CGEXPR
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING CGEXHD,FIRST,TABLES,CGEXPR
;
;
;
OPGNCK:: .RUN DSK:MACRO[10,7]
*OPGNTA_OPGNTA
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING OPGNTA
;
;
;
.SET TTY NOBLANKS
PEEPCK:: .RUN DSK:BLIS10
*PEEPOP/S,PEEPOP.MAC/M_PEEPHD.BLI,FIRST,TABLES,PEEPOP.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING PEEPHD.BLI,FIRST,TABLES,PEEPOP.BLI
;
;
;
.SET TTY NOBLANKS
PHA3CK:: .RUN DSK:BLIS10
*PHA3/S,PHA3.MAC/M_PHA3HD,FIRST,TABLES,PHA3,END.BLI
.IF (ERROR).PLEASE FRTCOM - ERROR IN COMPILING PHA3HD,FIRST,TABLES,PHA3,END
;
;
;
; ALL PHASE 3 SOURCES ARE NOW COMPILED.  LET'S LOAD PHASE 3.
P3CK:: .PLEASE FRTCOM - LOADING PHASE 3 OF FORTRAN COMPILER
.TYPE P3.CMD
.RUN DSK:LOADER[10,7]
*P3.CMD@
.SSAVE FORTG
.PLEASE FRTCOM - PHASE 3 FORTRAN COMPILE SUCCESSFUL   
.GOTO P3END

%ERR:
%CERR:.PLEASE FRTCOM - ERROR IN PHASE 3 FORTRAN COMPILE   
.GOTO END
;
;
P3END:
;
; THIS IS THE END OF THE PHASE 3 BUILDING SECTION.
;333333333333333333333333333333333333333333333333333333333333
;
;
.PLEASE FRTCOM - FORTRAN COMPILER LOADED AND SAVED
; NOW THAT COMPILER BUILDING IS COMPLETE, LET'S GET A
; CHECKSUMMED DIRECTORY OF ALL FILES.

; ENTRY POINT TO MAKE THE RELEASE TAPES FOR FORTRAN
MKTAP::.ERROR
.PLEASE FRTCOM - GETTING CHECKSUMMED DIRECTORY OF ENTIRE DSK AREA   
.DIR/CHECKSUM
;
;
; END OF FORTRAN.CTL
; FILENAME:	GLOB0.CTL
; DATE:		18 JAN 73
; AUTHOR:	M. G. MANUGIAN
;
;
; FUNCTION:	GENERATES GLOB LISTINGS OF PHASE 0 OF FORTRA.
;
;
.PLEASE FRTCOM - GENERATE THE GLOB LISTINGS FOR FORTRAN
.R GLOB
*PATCH.REL
*MAIN.REL
*GLOBAL.REL
*STATOU.REL
*ERR3.REL
*SCAN.REL[10,7]
*WILD.REL[10,7]
*COMMAN.REL
*JOBD.REL
*HELPER.REL[10,7]
*JOBDAT.REL[10,7]
*DSK:0A.GLB_
*DSK:0E.GLB_/E
*DSK:0N.GLB_/N
*DSK:0M.GLB_/S
;
;
; END OF GLOB0.CTL
; FILENAME:	GLOB1.CTL
; DATE:		18 JAN 73
; AUTHOR:	M. G. MANUGIAN
;
;
; FUNCTION:	GENERATES GLOB LISTINGS OF PHASE 1 OF FORTRAN.
;
;
;
.R GLOB
*PATCH.REL
*MAIN.REL
*GLOBAL.REL
*SRCA.REL
*INOUT.REL
*ERROUT.REL
*STATOU.REL
*ERR3.REL
*SRCB.REL
*FLTGEN.REL
*VLTPPR.REL
*ARRXPN.REL
*MAKEPR.REL
*DOXPN.REL
*CNSTCM.REL
*DPSIM.REL
*FAZ1.REL
*GNRCFN.REL
*EXPRES.REL
*FORMAT.REL
*ACT0.REL
*ACT1.REL
*STA0.REL
*STA1.REL
*STA2.REL
*STA3.REL
*CLASS.REL
*JOBD.REL
*JOBDAT.REL[10,7]
*DSK:1A.GLB_
*DSK:1E.GLB_/E
*DSK:1N.GLB_/N
*DSK:1M.GLB_/S
;
;
;
; END OF GLOB1.CTL
; FILENAME:	GLOB2.CTL
; DATE:		18 JAN 73
; AUTHOR:	M. G. MANUGIAN
;
;
; FUNCTION:	GENERATES GLOB LISTINGS OF PHASE 2 OF FORTRAN.
;
;
;
;
.R GLOB
*PATCH.REL
*MAIN.REL
*GLOBAL.REL
*SRCA.REL
*INOUT.REL
*ERROUT.REL
*STATOU.REL
*ERR3.REL
*CNSTCM.REL
*SKSTMN.REL
*P2S1.REL
*P2S2.REL
*MEMCMP.REL
*CANNON.REL
*COMSUB.REL
*MAKEPR.REL
*DPSIM.REL
*GOPTIM.REL
*UTIL.REL
*GRAPH.REL
*DEFPT.REL
*PNROPT.REL
*PHA2.REL
*JOBD.REL
*JOBDAT.REL[10,7]
*DSK:2A.GLB_
*DSK:2E.GLB_/E
*DSK:2N.GLB_/N
*DSK:2M.GLB_/S
;
;
; END OF GLOB2.CTL
; FILENAME:	GLOB2S.CTL
; DATE:		18 JAN 73
; AUTHOR:	M. G. MANUGIAN
;
;
; FUNCTION:	GENERATES GLOB LISTINGS OF PHASE 2S OF FORTRAN.
;
;
;
;
.R GLOB
*PATCH.REL
*MAIN.REL
*GLOBAL.REL
*SRCA.REL
*INOUT.REL
*ERROUT.REL
*STATOU.REL
*ERR3.REL
*CNSTCM.REL
*SKSTMN.REL
*P2S1.REL
*P2S2.REL
*MEMCMP.REL
*CANNON.REL
*COMSUB.REL
*MAKEPR.REL
*DPSIM.REL
*GOPTIM.REL
*UTIL.REL
*PH2S.REL
*JOBD.REL
*JOBDAT.REL[10,7]
*DSK:2SA.GLB_
*DSK:2SE.GLB_/E
*DSK:2SN.GLB_/N
*DSK:2SM.GLB_/S
;
;
; END OF GLOB2S.CTL
; FILENAME:	GLOB3.CTL
; DATE:		18 JAN 73
; AUTHOR:	M. G. MANUGIAN
;
;
; FUNCTION:	GENERATES GLOB LISTINGS OF PHASE 3 OF FORTRAN.
;
;
;
;
.R GLOB
*PATCH.REL
*MAIN.REL
*GLOBAL.REL
*SRCA.REL
*INOUT.REL
*ERROUT.REL
*STATOU.REL
*ERR3.REL
*OPTAB.REL
*LISTOU.REL
*CGDO.REL
*CGSTMN.REL
*CGEXPR.REL
*OPGNTA.REL
*MAKEPR.REL
*PEEPOP.REL
*UTIL.REL
*GOPTIM.REL
*CNSTCM.REL
*DPSIM.REL
*PHA3.REL
*JOBD.REL
*JOBDAT.REL[10,7]
*DSK:3A.GLB_
*DSK:3E.GLB_/E
*DSK:3N.GLB_/N
*DSK:3M.GLB_/S
;
;
; END OF GLOB3.CTL
; FILENAME:	GLOB3G.CTL
; DATE:		18 JAN 73
; AUTHOR:	M. G. MANUGIAN
;
;
; FUNCTION:	GENERATES GLOB LISTINGS OF PHASE 3G OF FORTRAN.
;
;
.R GLOB
*PATCH.REL
*MAIN.REL
*GLOBAL.REL
*SRCA.REL
*INOUT.REL
*ERROUT.REL
*STATOU.REL
*ERR3.REL
*ARRXPN.REL
*VLTPPR.REL
*CNSTCM.REL
*STREGA.REL
*DPSIM.REL
*CMPLEX.REL
*DOALC.REL
*REGAL2.REL
*MAKEPR.REL
*UTIL.REL
*DATAST.REL
*OUTMOD.REL
*GOPTIM.REL
*PH3G.REL
*JOBD.REL
*JOBDAT.REL[10,7]
*DSK:3GA.GLB_
*DSK:3GE.GLB_/E
*DSK:3GN.GLB_/N
*DSK:3GM.GLB_/S
;
;
;
; END OF GLOB3G.CTL
; FILENAME:	GLOB3R.CTL
; DATE:		18 JAN 73
; AUTHOR:	M. G. MANUGIAN
;
;
; FUNCTION:	GENERATES GLOB LISTINGS OF PHASE 3R OF FORTRAN.
;
;
;
;
.R GLOB
*PATCH.REL
*MAIN.REL
*GLOBAL.REL
*SRCA.REL
*INOUT.REL
*ERROUT.REL
*STATOU.REL
*ERR3.REL
*ARRXPN.REL
*VLTPPR.REL
*CNSTCM.REL
*DPSIM.REL
*STREGA.REL
*CMPLEX.REL
*DOALC.REL
*REGAL2.REL
*MAKEPR.REL
*UTIL.REL
*DATAST.REL
*OUTMOD.REL
*LISTOU.REL
*GOPTIM.REL
*P3R.REL
*JOBD.REL
*JOBDAT.REL[10,7]
*DSK:3RA.GLB_
*DSK:3RE.GLB_/E
*DSK:3RN.GLB_/N
*DSK:3RM.GLB_/S
;
;
; END OF GLOB3R.CTL

;SKIP PAST THESE COMPILATIONS
.GOTO FSD
RT::.MOUNT BLKC/VID:'FRTCOM - FORTRAN COMPILER'
.IF (NOERROR) .GOTO RA
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO RT

RA::.NOERROR
.COPY DSK:=BLK:[7,1142]LOADER.MAC,COMPIL.MAC,CML022.RND,LDR057.RND

.DISMOUNT BLKC/VID:'FRTCOM - FORTRAN COMPILER'/REMOVE
.ERROR

.RUN MACRO[10,7]
*LOADER_LOADER
*COMPIL_COMPIL
.RUN LOADER[10,7]
*COMPIL
.SSAV
.RUN LOADER[10,7]
*LOADER
.SSAV

RELEN::.CHKPNT RELEN
.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO FSD
.PLEASE MOUNT THE PACK & PROCEED OR KILL THIS JOB
.BACKTO RELEN
FSD::.NOERROR
; FILENAME:	FCUSP.CTL
; DATE:		1 FEB 73
;
; FUNCTION:	GENERATES THE CUSP PORTION OF THE FORTRAN SYSTEM
;		RELEASE TAPE.  IT EXPANDS RNDFILES INTO DOC FILES
;		AND SAVES ALL ON-LINE DOCUMENTATION FILES WITH
;		CORE IMAGES OF FORTRAN RELATED CUSPS.
;
;
;
; FIRST EXPAND ALL RND FILES INTO DOC FILES.
.RUN DSK:RUNOFF[10,7]
*BAKWDS.RND
*BAKWDS.DOC
;
;
;
.RUN DSK:RUNOFF[10,7]
*CML022.RND
*COMPIL.DOC
;
;
;
.RUN DSK:RUNOFF[10,7]
*FRS002.RND
*FOROTS.DOC
;
;
;
.RUN DSK:RUNOFF[10,7]
*FTR001.RND
*FORTRA.DOC
;
;
;
.RUN DSK:RUNOFF[10,7]
*FTR001.RNF
*FTR001.FIG
;
;
;
.RUN DSK:RUNOFF[10,7]
*LDR057.RND
*LOADER.DOC
;
;
;
; NOW ALL DOC FILES HAVE BEEN GENERATED, LET US DO THE SAVE.

; END OF FCUSP.CTL
; PRINT ALL DOCUMENTATION FILES
.PRINT  *.DOC,*.HLP,*.BWR,*.QAS,*.FIG,QERROR.FRM
.PRINT  *.DOC,*.HLP,*.BWR,*.QAS,*.FIG,QERROR.FRM
.PRINT  *.DOC,*.HLP,*.BWR,*.QAS,*.FIG,QERROR.FRM
.PRINT *.GLB
.PLEASE FRTCOM - OPER COLLECT THE 4 SETS OF LISTINGS FOR FORTRAN   
;
DIRST::.CHKPNT DIRST
.ERROR

; IT IS ASSUMED THE OLD DIRECTORIES ARE ON THE USER'S AREA UNDER
; THE NAME ???FTR.DIR
.COPY FOO.TMP=???FTR.DIR
.R TECO
*ERFOO.TMPEW311.CMPY
*_[31,1]0LB,.KL
*:N[31,1]"SL.,ZK'HPEF
*ERFOO.TMPEW312.CMPY
*_[31,2]0LB,.KL
*:N[31,2]"SL.,ZK'HPEF
;
; MAKE DUMMY DIRECTORIES FOR NOW
.DIRECT 311=FOR1:[31,1]/CHECKSUM
.DIRECT 312=FOR1:[31,2]/CHECKSUM

; NOW MAKE A DUMMY NEW FILE
.MAKE 00FILE.NEW
*EX

; NOW GET THE PROPER MONTH FOR THE OUTPUT TAPE BY RUNNING THE
; PROGRAM FRTMON.SHR. IT QUERIES THE OPERATOR AT THE CONSOLE
; AND CREATES A PIP INDIRECT FILE NAMED FTRMON.CCL.

FRTMN:: .CHKPNT FRTMN
.OPERATOR %
.RUN FRTMON
.NOOPERATOR

; NOW PUT THESE DUMMY FILES INTO THE RELEASE AREA
; BUT FIRST MODIFY THE OUTPUT PROTECTION
.TECO FTRMON.CCL
*<FN<155><100>;>EX
.R PIP
*FTRMON@
.DELETE FTRMON.CCL
.RENAME FTRMON.CCL=FTRMON.BAK

; NOW DO THE SAVING.
.R PIP
*FRTSAV.CCL@
.IF (ERROR)

; NOW TRANSFER ALL FILES TO THE RELEASE TAPE AREAS
.R PIP
*FRTREL.CCL@
.IF (ERROR)

; NOW GET THE REAL DIRECTORIES FOR THESE AREAS
.DIRECT 311=FOR1:[31,1]/CHECKSUM
.DIRECT 312=FOR1:[31,2]/CHECKSUM

.R SCDCP
*311.NEW=311.DIR,311.CMP/N
.IF (ERROR)
*312.NEW=312.DIR,312.CMP/N
.IF (ERROR)

; NOW MERGE THE TWO FILES INTO ONE
.R TECO
*EW00FILE.NEW
*ER312.NEWYI	New files on [1,5] CUSP area
*
*
*<--1;P>P
*ER311.NEWY12II	New files on [10,6] Release area
*
*
*EX
;
; NOW PUT THE DIRECTORIES ONTO THE RELEASE AREA USING THE
; NEWLY FORMATTED NAMES IN THE FORM ???FTR.DIR & ???FTR.NEW
.TYPE FTRMON.CCL
.IF (ERROR)
.R PIP
*FTRMON@

MTTAP::.MOUNT FOR1/VID:'FORTRAN COMPILER PACK'
.IF (NOERROR) .GOTO SETSC
.PLEASE FRTCOM - MOUNT THE PACK AND PROCEED OR KILL THIS JOB
.BACKTO MTTAP

SETSC::; NOW CHANGE THE SEARCH LIST SO WE DON'T SAVE EXTRANEOUS UFD'S
.PLEASE FRTCOM - PREPARE TO MAKE THE FORTRAN TAPE
.R SETSRC
*C FOR1
*T
;
; NOW PREPARE TO MAKE THE TAPE
.MOUNT MTA:FAILSA/VID:'FORTRAN RELEASE TAPE'/WE
.IF (ERROR) .GOTO RETRY

.OPERATOR %
.R FAILSA
*/W
*/G 31,2
*/O 1,5
*/U
; NOW SAVE THE CUSP AREA
*/G 31,1
*/O 10,6
*/U
.NOOPERATOR
;
;
; NOW GET A CHECKSUMMED DIRECTORY OF THE TAPE
.DIRECT FTRTAP.DIR=FAILSA:/CHECKSUM
;
; NOW MAKE SURE THE TAPE GOT WRITTEN PROPERLY
.NOERROR
.COPY FOO.TMP=FOR1:[31,1]???FTR.DIR
.R SCDCP
*FTRTAP.ERR=FTRTAP.DIR,FOO.TMP/N
.ERROR
.PRINT FOR1:???FTR.DIR[31,1],???FTR.NEW[31,1],FTRTAP.DIR
.IF (ERROR)
;
; NOW DISMOUNT THE TAPE
.UNLOAD FAILSA:
.DEASSIGN

.PLEASE FRTCOM SUCCESSFUL       
.GOTO END
;
RETRY:: ; REQUEUE FOR + 15 MINUTES
.PLEASE FRTCOM - RESUBMITTING FRTCOM TO RUN IN 15 MINUTES
.SUBMIT FRTCOM/TIME:1::/UNIQ:0/AFTER:+15/TAG:MTTAP
;
;
END::
; END OF RELEAS.CTL
%ERR::
%CERR::
%FIN::.PLEASE FRTCOM.CTL DONE
.PRINT FRTCOM.LOG/AFTER:+1
.K/F
.IF (ERROR) .DETACH
  h a≈