TITLE IC
 START: INIT 1,16
        SIXBIT/DSK/
        0
        JFCL
        INIT 2,16
        SIXBIT/DSK/
        0
        JFCL
        ENTER 1,TMPFIL
        JFCL
        CLOSE 1,
        LOOKUP 1,TMPFIL
        JFCL 
        ENTER  1,TMPFIL
        JFCL
        LOOKUP 2,TMPFIL
        JFCL
        SETZM 1
        RENAME 2,1
ERR:    JFCL
        CLOSE 2,
        EXIT

TMPFIL: SIXBIT/A/
        0
        0
        0
        END START
