DELETE THESE LINES CONTAINING THE INSTRUCTIONS.
SUBSTITUTE COW FOR COW.
PUT PERIOD AT END OF EACH SENTENCE.
CORRECT SPELLING OF QUICK.
TAKE SPACE OUT OF JUMPED.
MOVE THE WORD THE IN 'THE QUICK BROWN FOX' TO THE FIRST PRINT POS.
THE QUICK BROWN FOX.
JUMPED OVER THE LAZY COW.
THE QUICK BROWN FOX.
JUMPED OVER THE LAZY COW.
THE QUICK BROWN FOX.
JUMPED OVER THE LAZY COW.
THE QUICK BROWN FOX.
JUMPED OVER THE LAZY COW.
