;LIBOL.CTL		%EDIT=17
;USED TO MAKE LIBOL FROM LIBOL SOURCE FILES
;SUBMIT WITH COMMAND	.SUBMIT LIBOL/TIME:10000

;COPYRIGHT 1973, DIGITAL EQUIPMENT CORP., MAYNARD, MASS.
;
;REQUIRED FILES:
;DSKB:[10,7]	PIP.SHR		(LATEST RELEASED VERSIONS)
;		LOADER.SHR
;		MACRO.SHR
;		FUDGE2.SHR
;		DIRECT.SHR
;		COMPIL.SHR
;		CREF.SHR
;		JOBDAT.REL
;[SELF]	LIBOL.CTL	LIBOL.DOC
;	ACCEPT.MAC	DPDIV.MAC	KEY.MAC		PERF.MAC
;	ALPHAS.MAC	DPMUL.MAC	KPROG.MAC	POS67.MAC
;	ARGS.MAC	CANCEL.MAC	PUTRES.MAC
;	CBLIO.MAC	DPSUB.MAC	LIBIMP.MAC	SETRET.MAC
;	CD6776.MAC	DSPFP.MAC	LINE.MAC	SIZ23.MAC
;	CMPX.MAC	EDIT.MAC	MAGNEG.MAC	SIZE1.MAC
;	CMPARE.MAC	EXAM.MAC	MOVE.MAC	SPACES.MAC
;	COMPD.MAC	EXPON.MAC	NEG67.MAC	SUBSCR.MAC
;	CSORT.MAC	FIX.MAC		NUMBRS.MAC	TRACED.MAC
;	DCVDIG.MAC	FLOT1.MAC	OVRLAY.MAC	UUO.MAC
;	DIV11.MAC	FLOT2.MAC	PD67.MAC	UUODSP.MAC
;	DPADD.MAC	GD67.MAC	PDL.MAC		ZEROES.MAC
;
;OUTPUT: LIBOL.REL & LIBOL6.SHR
;
;OUTPUT LISTINGS: LIBOL.LOG, LIBOL.DOC(3)
;	LIBOL.CTL DOES NOT NORMALLY PRODUCE LISTINGS OF THE ASSEMBLED
;	SOURCES.  IF LISTINGS ARE DESIRED, THE USER SHOULD INCLUDE A
;	FILE CALLED LISTEM.MAC IN HIS AREA.  THIS FILE SHOULD BE EMPTY.
;
;COPY FILES FROM [10,7] AND USE PRIVATE SYS:
.RUN DSKB:PIP[10,7]
*/X=DSKB:[10,7]PIP.SHR,LOADER.SHR,MACRO.SHR,FUDGE2.SHR,DIRECT.SHR
*/X=DSKB:[10,7]COMPIL.SHR,CREF.SHR,JOBDAT.REL
.IF (ERROR) .GOTO TRUBLE
.ASSIGN DSK: SYS:
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
.DIRECTORY/CHECKSUM *.SHR
.GOTO A
A:.DIRECTORY/CHECKSUM *.MAC+JOBDAT.REL+LIBOL.CTL+LIBOL.DOC
;ASSEMBLE SOURCES
;
.R MACRO
*ACCEPT,ACCEPT/C=ACCEPT
*ALPHAS,ALPHAS/C=ALPHAS
*ARGS,ARGS/C=ARGS
*CANCEL,CANCEL/C=CANCEL
*CBLIO,CBLIO/C=CBLIO
*CD6776,CD6776/C=CD6776
*CMPX,CMPX/C=CMPX
*CMPARE,CMPARE/C=CMPARE
*COMPD,COMPD/C=COMPD
*CSORT,CSORT/C=CSORT
*DCVDIG,DCVDIG/C=DCVDIG
*DIV11,DIV11/C=DIV11
*DPADD,DPADD/C=DPADD
*DPDIV,DPDIV/C=DPDIV
*DPMUL,DPMUL/C=DPMUL
*DPSUB,DPSUB/C=DPSUB
*DSPFP,DSPFP/C=DSPFP
*EDIT,EDIT/C=EDIT
*EXAM,EXAM/C=EXAM
*EXPON,EXPON/C=EXPON
*FIX,FIX/C=FIX
*FLOT1,FLOT1/C=FLOT1
*FLOT2,FLOT2/C=FLOT2
*GD67,GD67/C=GD67
*KEY,KEY/C=KEY
*KPROG,KPROG/C=KPROG
*LIBIMP,LIBIMP/C=LIBIMP
*LINE,LINE/C=LINE
*MAGNEG,MAGNEG/C=MAGNEG
*MOVE,MOVE/C=MOVE
*NEG67,NEG67/C=NEG67
*NUMBRS,NUMBRS/C=NUMBRS
*OVRLAY,OVRLAY/C=OVRLAY
*PD67,PD67/C=PD67
*PDL,PDL/C=PDL
*PERF,PERF/C=PERF
*POS67,POS67/C=POS67
*PUTRES,PUTRES/C=PUTRES
*SETRET,SETRET/C=SETRET
*SIZ23,SIZ23/C=SIZ23
*SIZE1,SIZE1/C=SIZE1
*SPACES,SPACES/C=SPACES
*SUBSCR,SUBSCR/C=SUBSCR
*TRACED,TRACED/C=TRACED
*UUO,UUO/C=UUO
*UUODSP,UUODSP/C=UUODSP
*ZEROES,ZEROES/C=ZEROES
.IF (ERROR) .GOTO TRUBLE
;CREATE LISTINGS IF FILE LISTEM.MAC IS PRESENT
;
.TYPE LISTEM.MAC
.IF (ERROR) .GOTO ENDLST
;
.R CREF
*ACCEPT.LST=ACCEPT
*ALPHAS.LST=ALPHAS
*ARGS.LST=ARGS
*CANCEL.LST=CANCEL
*CBLIO.LST=CBLIO
*CD6776.LST=CD6776
*CMPX.LST=CMPX
*CMPARE.LST=CMPARE
*COMPD.LST=COMPD
*CSORT.LST=CSORT
*DCVDIG.LST=DCVDIG
*DIV11.LST=DIV11
*DPADD.LST=DPADD
*DPDIV.LST=DPDIV
*DPMUL.LST=DPMUL
*DPSUB.LST=DPSUB
*DSPFP.LST=DSPFP
*EDIT.LST=EDIT
*EXAM.LST=EXAM
*EXPON.LST=EXPON
*FIX.LST=FIX
*FLOT1.LST=FLOT1
*FLOT2.LST=FLOT2
*GD67.LST=GD67
*KEY.LST=KEY
*KPROG.LST=KPROG
*LIBIMP.LST=LIBIMP
*LINE.LST=LINE
*MAGNEG.LST=MAGNEG
*MOVE.LST=MOVE
*NEG67.LST=NEG67
*NUMBRS.LST=NUMBRS
*OVRLAY.LST=OVRLAY
*PD67.LST=PD67
*PDL.LST=PDL
*PERF.LST=PERF
*POS67.LST=POS67
*PUTRES.LST=PUTRES
*SETRET.LST=SETRET
*SIZ23.LST=SIZ23
*SIZE1.LST=SIZE1
*SPACES.LST=SPACES
*SUBSCR.LST=SUBSCR
*TRACED.LST=TRACED
*UUO.LST=UUO
*UUODSP.LST=UUODSP
*ZEROES.LST=ZEROES
.IF (ERROR) .GOTO TRUBLE
ENDLST::;GO TO NEXT PAGE
;CREATE LIBOL.REL
.R PIP
*LIBOL.REL/B=TRACED.REL,CBLIO.REL,LIBIMP.REL,UUO.REL,UUODSP.REL,PDL.REL,LINE.REL
*LIBOL.REL/B=LIBOL.REL,ACCEPT.REL,ARGS.REL,PUTRES.REL,CANCEL.REL,GD67.REL,PD67.REL,FLOT1.REL
*LIBOL.REL/B=LIBOL.REL,FLOT2.REL,FIX.REL,CD6776.REL,MOVE.REL,EXPON.REL,COMPD.REL,CMPX.REL
*LIBOL.REL/B=LIBOL.REL,CMPARE.REL,SPACES.REL,ALPHAS.REL,ZEROES.REL,POS67.REL,NEG67.REL,NUMBRS.REL
*LIBOL.REL/B=LIBOL.REL,DSPFP.REL,DIV11.REL,DPDIV.REL,DPADD.REL,DPSUB.REL,DPMUL.REL,MAGNEG.REL
*LIBOL.REL/B=LIBOL.REL,SUBSCR.REL,SIZE1.REL,SIZ23.REL,EXAM.REL,EDIT.REL,DCVDIG.REL,PERF.REL
*LIBOL.REL/B=LIBOL.REL,OVRLAY.REL,KEY.REL,KPROG.REL,CSORT.REL,SETRET.REL
.IF (ERROR) .GOTO TRUBLE
;
;
;THROW AWAY LOCAL SYMBOLS FROM LIBOL.REL
.R FUDGE2
=LIBOL.REL/X=LIBOL.REL
.IF (ERROR) .GOTO TRUBLE
;
;
;CREATE PURE VERSION OF LIBIMP
.R MACRO
*LIBS=TTY:,DSK:LIBIMP
*COMFLG==1
=^Z
=^Z
.IF (ERROR) .GOTO TRUBLE
;
;
;CREATE LIBOL6.SHR
.R LOADER
=LIBOL6.MAP=LIBS,LIBOL/L/M
.IF (ERROR) .GOTO TRUBLE
.SSAVE DSK:LIBOL6
.IF (ERROR) .GOTO TRUBLE
;
;SEE WHAT WE GOT
.DIRECTORY/CHECKSUM LIBOL.REL+LIBOL6.SHR
;
.DEASSIGN SYS:
.QUEUE LIBOL.DOC/COPIES:3,*.LST
.IF (ERROR) .PLEASE COULDN'T PRINT LIBOL DOCUMENTATION
;DELETE UNNEEDED FILES
.RUN DSK:PIP
*DSK:/D=TRACED.REL,LIBIMP.REL,CBLIO.REL,LIBS.REL,UUO.REL,UUODSP.REL
*DSK:/D=PDL.REL,ACCEPT.REL,LINE.REL,ARGS.REL,PUTRES.REL,CANCEL.REL
*DSK:/D=GD67.REL,PD67.REL,FLOT1.REL,FLOT2.REL,FIX.REL,CD6776.REL,MOVE.REL
*DSK:/D=EXPON.REL,COMPD.REL,CMPX.REL,CMPARE.REL,SPACES.REL,ALPHAS.REL,ZEROES.REL
*DSK:/D=POS67.REL,NEG67.REL,NUMBRS.REL,DSPFP.REL,DIV11.REL,DPDIV.REL
*DSK:/D=DPADD.REL,DPSUB.REL,DPMUL.REL,MAGNEG.REL,SUBSCR.REL
*DSK:/D=SIZE1.REL,SIZ23.REL,EXAM.REL,EDIT.REL,DCVDIG.REL,PERF.REL
*DSK:/D=OVRLAY.REL,KEY.REL,KPROG.REL,CSORT.REL,SETRET.REL
*DSK:/D=LOADER.SHR,MACRO.SHR,DIRECT.SHR,COMPIL.SHR,CREF.SHR,JOBDAT.REL
*DSK:/D=FUDGE2.SHR,PIP.SHR,*.CRF
.IF (ERROR) .PLEASE -- ERRORS DELETING LIBOL FILES
;
;
;TELL OPERATOR HOW WE DID
.PLEASE -- LIBOL CREATION SUCCESSFUL
.GOTO OK
TRUBLE:.PLEASE -- LIBOL CREATION NOT SUCCESSFUL!!!
OK::.;END OF LIBOL.CTL
