;JOB%1(15) TO MAKE LOGIN.SHR FROM LOGIN.MAC
;SUBMIT WITH COMMAND  .QUEUE I:=LOGIN/RESTART:1
;
;REQUIRED FILES:  (LATEST RELEASED VERSIONS)
;[10,7]	PIP.SHR
;	DIRECT.SHR
;	COMPIL.SHR
;	MACRO.SHR
;	LOADER.SHR
;	JOBDAT.REL
;	CREF.SHR
;[SELF]	LOGIN.MAC
;
;OUTPUT FILE:
;	LOGIN.SHR
;OUTPUT LISTINGS:
;	LOGIN  MAP
;	LOGIN  CREF LISTING
;	LOGIN.LOG
;
;
;COPY FILES FROM [10,7] AND USE PRIVATE "SYS:"
.RUN DSK:PIP[10,7]
*/X_DSK:PIP.SHR[10,7],COMPIL.SHR[10,7],MACRO.SHR[10,7],LOADER.SHR[10,7]
*/X_DSK:JOBDAT.REL[10,7],CREF.SHR[10,7]
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=*.SAV+*.SHR+*.HLP
.GOTO A
A:.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=LOGIN.MAC,JOBDAT.REL,LOGIN.DOC
*TTY:/CHECKSUM=LOGIN.CTL,LOGIN.COR,LGI???.RND
;****HERE INCLUDE OTHER SUBROUTINES AND THERE CHECKSUM****
;*****EXAMPLES ARE SCANER,QUEUER ETC                 *****
.ASSIGN DSK: SYS:
;
;COMPILE, LOAD, AND SAVE; PRODUCING MAP AND CREF FILE
.LOAD /MAP:LPT:LOGIN /CREF /COMPILE LOGIN.MAC %A
.SSAVE DSK:LOGIN
.VERSION
.IF (ERROR) .E 137
;
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=LOGIN.SHR+LOGIN.LOW+LOGIN.SAV
;
;PRODUCE SOURCE LISTING AND TELL OPERATOR
.CREF
.PLEASE LOGIN SUCCESSFUL
;
;REMOVE ALL TEMPORARY FILES
%FIN: .DELETE LOGIN.REL,MACRO.SHR,LOADER.SHR,CREF.SHR
.IF (ERROR) ;DON'T CARE IF FAILED
.DELETE COMPIL.SHR,PIP.SHR,JOBDAT.REL
