      SUBROUTINE ACNUM( IAC )
C			     NO COMMON NEEDED
C			     BRING BACK A NUMBER BETWEEN 0 AND 3
C			     FILED MUST BE ABS
      IAC = 0
      CALL EXPRES( IAC, IT, MO)
      IAC=IABS(IAC)
C			     CHECK THAT ONLY ONE WORD MODE
      IF( MO.NE.1 .OR. IT.NE.1 ) GO TO 50
C			     CHECK THAT IT'S IN RANGE
      IF( IAC.GE.0 .AND. IAC.LE.3 ) RETURN
C			     AC IS OUT OF RANGE
      CALL ERROR(1HO)
      GO TO 55
C
C			     AC IS REL OR D.P.
 50   CONTINUE
      CALL ERROR( 1HR )
 55   CONTINUE
      IAC = 0
      RETURN
      END
      SUBROUTINE ADDREF
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C
C
C			     IGNORE ON PASS 1
      COMMON /REFER/ I
      DATA MMM/ O1777740/
      IF( PASS1 ) RETURN
C
C			     GET X REF PTR
      J = SYTYPE(I)
      IF (.NOT. XREF) GO TO 37
C			     CHECK FOR ROOM IN TABLE
      IF( NREF - NREFX ) 30,20,10
C			     OVERFLOW IGNORE
   10 CONTINUE
      RETURN
C			     FIRST OVERFLOW OUTPUT MESSAGE
   20 CONTINUE
      NREF = NREF +1
      TYPE 1000
 1000 FORMAT(//' *** CROSS REF OVERFLOW ***'// )
      RETURN
   30 CONTINUE
      IPTR = IRIGHT(J,6)
C			     IF( CHAIN ALREADY STARTED )
      IF( IPTR .NE. 0 ) GO TO 40
      SYTYPE(I) = IOR(J, ILEFT(NREF+1, 6) )
C			     OK TO ADD
C
    5 NREF = NREF +1
C			     GO TO NEXT EMPTY BLOCK
      CROSS(1,NREF) = 0
      CROSS(2,NREF) = 0
      CROSS(3,NREF) = 0
      IPTR = NREF
      L = 2
C			     FILL EMPTY SLOT
   35 CONTINUE
      CROSS(L,IPTR) = ICARD
   37 IF( IAND(J, 31) .LE. 24) RETURN
C			     THIS REFERENCE IS TO AN EXTERNAL
C			     RESET THE VALUE AND TYPE OF THE SYMBOL
      SYTYPE(I) = IAND(J,MMM) + IMODE + 24
      SYVALU(I) = LOCCNT
      RETURN
C
C			     SEARCH FOR END OF CHAIN
   40 CONTINUE
      IF( CROSS(1,IPTR) .EQ. 0 ) GO TO 50
      IPTR = CROSS(1,IPTR)
      GO TO 40
C
C			     END OF CHAIN IS THERE EMPTY SLOT
   50 CONTINUE
      L = 3
      IF( CROSS(3,IPTR) .EQ. 0 ) GO TO 35
C			     NO EMPTY SLOT CHAIN ON
      CROSS(1,IPTR) = NREF+1
      GO TO 5
C
      END
      SUBROUTINE ADDRES( IADRES, KTYPE )
C
C			     EVALUATE INSTRUCTION ADDRESS FIELD
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C
      DIMENSION IFGS(4,3,3)
      DATA  IFGS / 1,1,1,1,  1,1,1,1,  1,1,1,1,
     1		   9,9,9,9,  9,1,9,9,  9,9,9,9,
     2		   3,9,9,9,  3,9,9,9,  3,1,9,9	/
C
C			     EVALUATE EXPRESSION
      CALL EXPRES( IV, IT, MO)
      IV = IAND (IV,65535)
      IF( MO .NE. 1 ) GO TO 200
      IF( ERRFLG ) GO TO 55
C
C			     CHECK IF CARD IS FINISHED
       IF( LN(ICH).NE.64 .AND. LN(ICH).NE.ISEMI ) GO TO 10
C
C
      KTYPE = 6
      IADM = 0
C			     IS AN EXTERNAL DISPLACEMENT USED
      IF( IT .EQ. 6 ) GO TO 30
C
      IF( IT.LE.0 .OR. IT.GT.3 ) GO TO 201
C			     SET REGISTER NUMBER
      IFG = 4 - IT
      IF( IFG .LT. 3) GO TO 20
C
      IFG = 1
      IF( IV .GE. 256 ) IFG = 2
      IF( IFG.EQ.2 .AND. IMODE.GT.1 ) GO TO 202
      GO TO 20
C
C
   10 CONTINUE
C			     REGISTER IS USED
      CALL ACNUM(IFG)
      IADM = IFG
      IFG = IFG + 1
      KTYPE = 6
      IF( IT .EQ. 6 ) GO TO 30
C
   20 CONTINUE
      KTYPE = IFGS(IFG,IMODE,IT)
      IADM = IABS(IFG - 1)
C
      IF( KTYPE .GT. 3) GO TO 203
      IF( IT.EQ.IMODE .AND. IADM.EQ.1 ) IV = IV - LOCCNT
C
C
C
   30 CONTINUE
      J = IV
      IF( IADM .GT. 0 ) J = J + 128
CAND OFF ALL EXTRANEOUS BITS BEFORE TESTING
      J = IAND (J,65535)
      IF( J.GE.0 .AND. J.LT.256 ) GO TO 70
C
   50 CONTINUE
C			     ERROR HAS OCCURED
      CALL ERROR(1HA)
   55 CONTINUE
      KTYPE = 1
      IV = 0
      IADM = 0
C
C
   70 CONTINUE
C			     PUT ADDRESS FIELD IN INSTRUCTION
      IADRES = IAND(IV+1024,255) + ILEFT(IADM,8)
      IF( INDRCT .NE. 0 ) IADRES = IOR(IADRES, 1024)
      RETURN
C
C
  200 CONTINUE
  201 CONTINUE
  202 CONTINUE
  203 CONTINUE
  204 CONTINUE
      GO TO 50
      END
      SUBROUTINE ADDSYM( NAME, IVALUE, ITYPE)
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
C
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      LOGICAL INO
C
C
C			     ADD A SYMBOL TO SYM TABLE
      IF( NAME .EQ. 0 ) RETURN
      IF( .NOT. PASS1 ) GO TO 100
C			     PASS 1  ACTUALLY ADD TO TABLE IF ROOM
C			     NS INITIALIZED TO POINT TO FIRST NON FIXED
      IF((NSYM+1) .GT. NSYMX ) GO TO 50
C			     ACTUALLY PUT INTO TABLE. NOTE X-REF PTR=0
      CALL LOSK(NAME,II,INO)
      IF(.NOT. INO) GO TO 30
      J=SYTYPE(II)
      IF(IAND(J,31).GT.6) RETURN
   30 CONTINUE
      IF( II .GT. NSYM ) GO TO 41
      L=NSYM
      DO 40 I=II,NSYM
      SYNAME(L+1)=SYNAME(L)
      SYTYPE(L+1)=SYTYPE(L)
      SYVALU(L+1)=SYVALU(L)
      L=L - 1
   40 CONTINUE
   41 CONTINUE
      IF( II.GT. NSYM+1 ) II = NSYM+1
      SYNAME(II)=NAME
      SYTYPE(II)=ITYPE
      SYVALU(II)=IVALUE
      NSYM = NSYM +1
C			     SYMBOL FOR PASS2
      RETURN
C			     TABLE FULL STOP WITH MESSAGE
   50 CONTINUE
      TYPE 1000
 1000 FORMAT(/' *** SYMBOL TABLE OVERFLOW, ABORTING ***'// )
      STOP
C
C			     THIS FLAGS BOTH OCCURANCES OF MULTIPLE USE
C			     PASS 2  LOOK AT ALL OTHER SYMBOLS FOR M ERR
  100 CONTINUE
      CALL LOSK(NAME,II,INO)
      J=SYTYPE(II)
      IF(INO.AND.(SYVALU(II).NE.IVALUE)) CALL ERROR(1HP)
      IF(.NOT.INO) CALL ERROR(1HP)
      JJ=IAND(J,31)
      IF((JJ.GT.7).AND.(JJ.LT.20)) CALL ERROR(1HC)
      IF(SYNAME(II+1).EQ.NAME) CALL ERROR(1HM)
C			     RETURN
      RETURN
      END
      SUBROUTINE ADNBLK( IVAL, IX, IAD, IT)
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     PROCESS A DATUM WORD FOR OUTPUT
C			     IT IS TYPE OF ADDRESS
C			     IX IS TYPE OF DATUM
C
C			     CHECK THAT THE ADDRESSES ARE SEQUENTIAL INC
C			     AND THAT THE DATUM MODE STAYS THE SAME
C
      IF( IADL.EQ.IAD .AND. IT.EQ.ITL ) GO TO 10
C			     CHANGE SO OUTPUT THE PREVIOUS BLK
      CALL PUTBLK
C			     RESET NEW BLOCK  ADDRESS AND TYPE
      IWDCT = 7
      IBL(7) = IAD
      CALL RELOC( IT )
      ITL = IT
      IADL = IAD
C
 10   CONTINUE
C			     NOW PUT IN THE DATUM WORD
      IADL = IADL  +  1
      IWDCT = IWDCT + 1
      IBL(IWDCT) = IVAL
C			     NOW DO THE RELOC BITS
      CALL RELOC( IX )
C			     CHECK IF THE BUFFER IS FULL
      IF( IWDCT .GE. 21 ) CALL PUTBLK
C
      RETURN
      END
      SUBROUTINE ADSBLK( NAME, IT, IVAL, IX)
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     PUT A SYMBOL INTO THE OUTPUT BUFFER
C			     IT IS TYPE OF NAME
C			     IX IS TYPE OF VALUE IVAL
C
C			     PROCESS THE VALUE RELOCATION BITS
      CALL RELOC( IX )
C			     CONVERT THE NAME TO 50 CODE
      CALL CONX( NAME , IBL(IWDCT+1) )
      IBL(IWDCT+2) = IBL(IWDCT+2) + IT
      IBL(IWDCT+3) = IVAL
C
      IWDCT = IWDCT + 3
C			     CHECK IF BLOCK FILLED UP
      IF( IWDCT .GE. 21 ) CALL PUTBLK
      RETURN
      END
      SUBROUTINE ASNAM (NEWNM)
C
C
      DIMENSION LNE(6)
C                             CONVERT INTERNAL CODE BACK TO PACKED ASCII
      J=NEWNM
      L = 6
      DO 10 I = 1,6
      K = IAND (J,63)
      IF (K.EQ.0) GO TO 5
      K = IASCII (K)
   5  LNE(L) = K
      L = L-1
      J = IRIGHT (J,6)
  10  CONTINUE
      J = 0
      DO 15 I = 1,5
      J = ILEFT (J,7) + LNE(I)
  15  CONTINUE
      NEWNM = ILEFT (J,1)
      RETURN
      END
      SUBROUTINE ATOM( IV, ITP, MODE )
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C
C			     FETCH THE NEXT ATOM FOR EVALUATION BY EXPRESS
C
    5 CONTINUE

C			     GO TO 30 IF AN OPERATOR
      IF( LN(ICH) .GT. INU9 ) GO TO 30
C			     GO TO 20 IF A NUMBER
      IF( LN(ICH) .GT. IPRD ) GO TO 20
C
C			     ITS A SYMBOL
      CALL GETSYM( NAME )
C			     SEE IF PERIOD IE LOCATION COUNTER
      IF( LNX(1).NE.IPRD .OR. NLNX.NE.1 ) GO TO 10
C			     ITS THE LOCATIONS COUNTER
      IV = LOCCNT
      ITP = IMODE
      MODE = 1
      RETURN
C
C			     LOOK UP THE SYMBOL
   10 CONTINUE
      CALL LOOKUP( NAME, IV, ITP)
      IF (ITP.EQ.15) ITP = 1
      IF(ITP.LE.7)  GO TO 15
      CALL ERROR(1HZ)
      IV=0
      ITP=1
      MODE=1
      RETURN
   15 CONTINUE
      CALL ADDREF
      MODE = 1
      RETURN
C
C			     ITS A NUMBER
   20 CONTINUE
      CALL GETNUM( IV, MODE)
      ITP = 1
      RETURN
C
C			     ITS AN OPERATOR CHECK IF END OF STM0T
   30 CONTINUE
      IF( LN(ICH) .EQ. 64 ) GO TO 52
      IF (LN(ICH) .EQ. ISEMI) GO TO 52
      IF(LN(ICH).EQ.IRAGL) GO TO 52
      DO 35 I=1,11
      IF( LN(ICH) .EQ. IPLUS-1+I ) GO TO 40
 35   CONTINUE
C			     CANT IDENTIFY THE OPERATOR
      ICH = 81
      MODE = 0
      IV = 0
      ITP = 1
      CALL ERROR(1HQ)
C			     SET TO END OF ATOMES
      RETURN
C
C			     HAVE THE OPERATOR
 40   IV = 0
      ITP = 1
      MODE = I+3
      ICH = ICH + 1
C			     IF ORDINARY OPER RETURN
      IF( I.LE. 6 ) RETURN
C
C			     FIND OUT WHATS UP NOW
      J = I-6
      IF( J .GT. 4 ) GO TO 52
      GO TO ( 51,52,53,54,55) ,J
C
C			     ITS A BLANK
   51 CONTINUE
      CALL SKPBLK
C			     ITS A COMA OR BLANK
   52 CONTINUE
      MODE = 0
      IV = 0
      ITP = 1
      RETURN
C
C			     ITS DOUBLE QUOTES
   53 CONTINUE
      IV = IASCII( LN(ICH) )
      ICH = ICH + 1
      ITP = 1
      MODE = 1
      RETURN
C
C			     ITS AN @ SET INDIRECT BIT AND GET NEXT
   54 CONTINUE
      INDRCT = 32768
      GO TO 5
C
C			     #	SET NOLOAD
   55 CONTINUE
      INOLOD = 8
      GO TO 5
      END
      SUBROUTINE BLOCK( IV )
C
C			     PROCESS .BLK STATEMENSS
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
      IWTYPE = 1
      NWDS = 0
      IOCLAS = 4
      IF( SKPFLG ) RETURN
      IOCLAS = 3
C			     ADD LABEL
      CALL ADDSYM( LABEL, LOCCNT, IMODE)
C			     EVALUATE EXRRESSION
      CALL EXPRES( IV, ITP, MO)
      IF( MO .EQ. 1 ) GO TO 5
      CALL ERROR(1HZ)
      GO TO 6
 5    CONTINUE
      IF( ITP .EQ. 1 .AND. IV.GE.0 ) GO TO 10
C			     INVALID EXPRESSION TYPE OR VALUE
      CALL ERROR( 1HR )
C
 6    CONTINUE
      IV = 0
      ITP = 1
   10 CONTINUE
C			     UPDATE LOCATION COUNTER
      LOCNXT = LOCCNT + IV
      IWORD(1) = IV
      RETURN
C
C
      END
      SUBROUTINE CAREND
C
C			     ALL REQUIRED FIELDS HAVE BEEN FOUND
C			     CHECK THE REST OF CARD
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C
      DO 10 I=ICH, 81
      IF(LN(I).NE.IBLNK) GO TO 20
   10 CONTINUE
C
   20 IF(LN(I).EQ.64.OR.LN(I).EQ.ISEMI) RETURN
      CALL ERROR(1HQ)
      RETURN
C
      END
      SUBROUTINE COMPCT
C
C
C			     REMOVE ALL SYMBOLS FROM SYMBOL TABLE
C			     EXCEPT OP-CODES
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      COMMON / XPNG / XPNFLG
      LOGICAL XPNFLG
C
C
C
      L = 0
      IF( NSYM .LE. 0 ) GO TO 11
C
      DO 10 I=1,NSYM
      J = SYTYPE(I)
C			     IS PRESENT SYMBOL AN OP-CODE
      IF( IAND(J,32)  .EQ. 0 ) GO TO 10
      IF (XPNFLG) GO TO 5
   3  L = L + 1
      SYNAME(L) = SYNAME(I)
      SYVALU(L) = SYVALU(I)
      SYTYPE(L) = IAND(J,63)
      GO TO 10
   5  IF (IAND(J,31) .EQ. 24) GO TO 3
   10 CONTINUE
C
   11  CONTINUE
      NSYM = L
      RETURN
C
C
      END
      SUBROUTINE CONSS( ISYM)
C			     CONVERT SYMBOL TO PACKED CODE
C
C
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODEG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     SET TO NULL SYMBOL
      ISYM = 0
C			     IF(NO CHARS) RETURN NULL SYMBOL
      IF( NLNX .LE. 0 ) RETURN
C			     IF( LESS THAN 5 CHARS) SET REMAINDER = 0
      IF( NLNX .GE. 5 ) GO TO 20
      J = NLNX+1
      DO 10 I=J,5
   10 LNX(I) = 0
C			     CONVERT FIRST FIVE CHARS TO INT CODE SYMBOL
C			     LEFT ADJ. 0 FILL
   20 CONTINUE
      J = 0
      DO 30 I=1,5
   30 J = J*64+LNX(I)
      ISYM = J*64
C
      RETURN
C
      END
      SUBROUTINE CONVRT( LINE)
C			     CONVERT INPUT CODE TO INTERNAL (HOLLERITH) CODE
C
C
      DIMENSION LINE(80) , ICODE(64)
      DATA ICODE  / 44,43,46,48,53,54,42,55,56,57,40,38,45,39,27,41,
     *28,29,30,31,32,33,34,35,36,37,50,49,51,63,52,58,
     *47,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
     *16,17,18,19,20,21,22,23,24,25,26,59,0,60,61,62 /
      DO 10 I=1,80
      L=IRIGHT(LINE(I),29)
      IF (L .LT. 32) L=32
      L=L-32
      J=IAND(L,63) + 1
      LINE(I)=ICODE(J)
 10   CONTINUE
      RETURN
      END
      SUBROUTINE CONV50(NM,IA)
C
C			     CONVERT FROM RADIX 50 CODE TO PRINT CODE
C
      DIMENSION IA(5)
      DIMENSION ICF(38)
      DATA ICF/1H ,
     1	1HA,1HB,1HC,1HD,1HE,1HF,1HG,1HH,1HI,1HJ,1HK,1HL,1HM,1HN,1HO,
     2 1HP,1HQ,1HR,1HS,1HT,1HU,1HV,1HW,1HX,1HY,1HZ,
     3	1H.,1H0,1H1,1H2,1H3,1H4,1H5,1H6,1H7,1H8,1H9/
      J = NM
      L = 6
C
      DO 10 I=1,6
C			     GET NEXT CHARACTER
      N = IAND(J,63) + 1
      IA(L) = ICF(N)
      L = L - 1
C			     SHIFT INPUT ONE CHARACTER RIGHT
   10 J = IRIGHT(J,6)
C
      RETURN
C
C
      END
      SUBROUTINE CONX( NAME, IBX )
C
C			     PREPARE SYMBOL NAME FOR OUTPUT ON TAPE
C
      DIMENSION IBX(2) , IN(6)
      N = NAME
C
      DO 10 I=1,6
      K = IAND( N,63)
C
      IF( K .EQ. 0 ) GO TO 9
      K = K + 10
C
      IF( K .GT. 37 ) K = K - 37
    9 CONTINUE
C
      N = IRIGHT(N,6)
   10 IN(I) = K
C
      IBX(1) = 1600*IN(6) + 40*IN(5) + IN(4)
      IBX(2) = ILEFT( 40*IN(3) + IN(2) ,5)
C
      RETURN
      END
      SUBROUTINE DEVICE(IDVC)
      CALL EXPRES(ID,IT,MO)
      IF(IT.NE.1.OR.MO.NE.1) GO TO 50
      IF(ID.GT.63.OR.ID.LT.0) GO TO 40
      IDVC=ID
      RETURN
   40 CALL ERROR(1HO)
      GO TO 55
   50 CALL ERROR(1HR)
   55 IDVC=0
      RETURN
      END
      SUBROUTINE ENDASM
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
      IF(.NOT. PTAPE) GO TO 30
C			     ASSEMBLY HAS BEEN COMPLETED
C			     OUTPUT ALL REMAINING SYMBOL BLOCKS
C			     AND START BLOCKS
      IF(RELASM) GO TO 10
C			     ABSOLUTE ASSEMBLY
C			     OUTPUT REST OF CODE
      CALL OUTOLD
      CALL STROLD
C			     OUTPUT START BLOCK
      IBL(1)=1
      IBL(2)= IWORD(1)
      IWDCT = 3
      CALL OUTOLX
      GO TO 20
C
C
   10 CALL PUTBLK
      CALL OUTNEX
C			     RELOCATABLE ASSEMBLY
      CALL OUTLOS
      CALL STRBLK(6)
      CALL RELOC (IWTYPE)
      IBL(7) = IWORD(1)
      IWDCT = 7
      CALL PUTBLK
   20 CALL LEADR(3)
C			     EMPTY OUTPUT BUFFERS
      CALL FLUSH
C
C
C			     PRINT CROSS REF. TABLE
   30 CALL XREFS
      IF( RELASM ) TYPE 1002
 1002 FORMAT(//' * RELOCATABLE ASSEMBLY *'/ )
      IF(.NOT.RELASM) TYPE 1003
 1003 FORMAT (//' * ABSOLUTE ASSEMBLY *'/ )
      IF (NEREF.EQ.0) GO TO 40
      TYPE 1000, NEREF
 1000 FORMAT(//' THERE WERE AT LEAST' I5,' ERRORS IN THIS ASSEM
     *BLY' //)
C
      IF( NEREF .GT. 0 ) TYPE 1001, (NEREFS(I),I=1,NEREF)
 1001 FORMAT(' ERRORS OCCURRED ON LINES' 8I6/10(12I6/))
C
C
      RETURN
   40 TYPE 1004
 1004 FORMAT (//,' THERE WERE NO ERRORS')
      RETURN
      END
      SUBROUTINE ENDS( IVALUE, ITYP)
C
C			     PROCESS .END, .EOT, .XPNG
C
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / XPNG / XPNFLG
      LOGICAL XPNFLG
C
C
      COMMON /ADDON1/ NEXTD,ASMEND
      LOGICAL ASMEND
C
C
      IOCLAS = 4
      NWDS =0
      J = IAND( IVALUE, 7 )
C			     IF( .EOT ) RETURN
      IF( J .EQ. 2 ) RETURN
C			     IF( .XPNG ) RETURN
      IF( J .EQ. 3 ) GO TO 70
C			     .END
      IOCLAS = 3
C			     EITHER EOF OR TWO CONSEQUITIVE END CARDS
      IF( ICARD .LE. 1 ) CALL FINASM
      ASMEND = .TRUE.
      CALL EXPRES( IV, ITYP, MO)
      IF( MO .NE. 1 ) GO TO 50
C
      IF( ITYP .GT. 3 ) GO TO 45
      IWTYPE = ITYP
      IWORD(1) = IV
C
      RETURN
C
C
C
 45   CONTINUE
      CALL ERROR( 1HR)
      GO TO 55
   50 CONTINUE
      CALL ERROR( 1HQ )
   55 CONTINUE
      IWORD(1) = 0
      IWTYPE = 1
      RETURN
C
   70 CONTINUE
C			     CLEAN OUT SYMBOL TABLE
      IF (.NOT. PASS1) RETURN
CDON'T BOTHER IF PASS 2
      XPNFLG = .TRUE.
      CALL COMPCT
      XPNFLG = .FALSE.
C
C
      RETURN
      END
   e e¬