      SUBROUTINE IATNOL
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
C
C
 5    CONTINUE
      IF( LN(ICH) .NE. IAT ) GO TO 15
      INDRCT = 32768
 10   CONTINUE
      ICH = ICH + 1
      GO TO 5
C
 15   CONTINUE
      IF( LN(ICH) .NE. INLOD ) RETURN
      INOLOD = 8
      GO TO 10
      END
      SUBROUTINE IFS( IVALUE)
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
C
C
      NWDS = 0
      IWORD(1) = 0
      IWTYPE = 1
      J = IAND( IVALUE, 7)
      IF( J .EQ. 3 ) GO TO 20
      IOCLAS = 3
      IF( IFMODE ) GO TO 50
      CALL EXPRES( IV, ITP, MO)
      IF( ITP.NE.1 .OR. MO.NE.1 ) GO TO 50
      IF (J.EQ. 1 .AND. IV .NE.0) SKPFLG = .TRUE.
      IF( J.EQ.2 .AND. IV.EQ.0 ) SKPFLG = .TRUE.
      IWORD(1) = IV
      IFMODE = .TRUE.
      RETURN
   20 CONTINUE
      IOCLAS = 4
      IF( .NOT. IFMODE ) GO TO 50
      SKPFLG = .FALSE.
      IFMODE = .FALSE.
      RETURN
   50 CONTINUE
      CALL ERROR( 1HK )
      RETURN
      END
      FUNCTION IOPER( IA, IB, IOP)
C
C			     PREFORM THE OPERATION SPECIFIED
C
      K = IOP - 3
      GO TO ( 10, 20, 30, 40, 50, 60) ,K
C
   10 J = IA + IB
      GO TO 100
C
   20 J = IA - IB
      GO TO 100
   30 J = IA * IB
      GO TO 100
   40 IF(IB .EQ. 0 ) GO TO 150
      J = IA / IB
      GO TO 100
   50 J = IAND( IA, IB)
      GO TO 100
   60 J = IOR( IA, IB)
C
  100 CONTINUE
      IOPER = J
      RETURN
C
C
  150 CONTINUE
      CALL ERROR( 1HZ)
      J = 0
      GO TO 100
C
      END
      FUNCTION IPARTY(K)
      J = 0
      DO 10 I=1,7
10	J = J + IAND(IRIGHT(K,I-1),1)
      IPARTY = MOD(J,2)
      RETURN
      END
      SUBROUTINE LEADR( N )
C			     PUNCH N FRAMES OF LEADER
      M = (N+1)/2
      DO 10 I=1,M
   10 CALL PNCH(0)
      RETURN
      END
      SUBROUTINE LISTOT
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
C
C
      COMMON /FILNM/ INAME,IONAME
      COMMON /XLIT/ NOLIST,EQFLG
      LOGICAL NOLIST,EQFLG
      DIMENSION IOCTV(6), IOCTL(6)
      DATA JBLNK /1H /
C			     OUTPUT THE LISTING
C
      IF( PASS1 ) RETURN
      IF( .NOT. ERRFLG	.OR. NEREF.GE.NEREFX ) GO TO 6
      NEREF = NEREF + 1
      NEREFS(NEREF) = ICARD
    6 CONTINUE
      IF (NOLIST) RETURN
      CALL STOPSP(KL)
C			     CHECK LINE COUNT
      IF( NLINE .LT. NLINEX ) GO TO 5
      CALL HEADR
      WRITE (IOFILE,1050)
 1050 FORMAT (/4X, 5HLINE   ,4X, 6HERRORS   ,3X, 6HLOC    ,5HVALUE ,
     *18X,11HINPUT LINE  / 4X, 'NUMBER')
 5    CONTINUE
      J = NCER+1
      DO  7 I=J,10
    7  NCERS(I) = JBLNK
C
      GO TO (10,10,30,40) , IOCLAS
C			     LOC TYPE VALUE TYPE CARD ERRORS ORDINAL
 10   CONTINUE
      IF( NWDS .LE. 0 ) GO TO 100
      DO 12 I=1,NWDS
      CALL OCTL( LOCCNT,IOCTL)
      CALL OCTL( IWORD(I), IOCTV )
      IF( I.GT.1 ) GO TO 11
      WRITE (IOFILE,1000) ICARD,NCERS,(IOCTL(J),J=2,6),ICLAS(IMODE),
     *IOCTV,ICLAS(IWTYPE),(ISOUR(K),K=1,KL)
 1000 FORMAT (2X,I5,3X,10A1,5I1,A1,3X,6I1,A1,4X,80A1 )
      GO TO 12
 11   CONTINUE
      WRITE (IOFILE,1100) (IOCTL(J),J=2,6),ICLAS(IMODE),IOCTV,
     *ICLAS(IWTYPE)
 1100 FORMAT (20X,5I1,A1,3X,6I1,A1)
      NLINE = NLINE + 1
      IF( NLINE .GT. NLINEX ) CALL HEADR
      IF( NLINE .GT. NLINEX ) WRITE (IOFILE,1050)
 12   LOCCNT = LOCCNT + 1
      LOCCNT = LOCCNT - NWDS
C
      GO TO 100
C
C
 30   CONTINUE
C			     VALUE TYPE CARD ETC.
      CALL OCTL( IWORD(1), IOCTV)
      WRITE (IOFILE,1001) ICARD,NCERS,IOCTV,ICLAS(IWTYPE),
     *(ISOUR(K),K=1,KL)
 1001 FORMAT (2X,I5,3X,10A1,9X,6I1,A1,4X,80A1)
      GO TO 100
C
C
C			     JUST A COMMENT TYPE NO NUMBERS
 40   CONTINUE
 1002 FORMAT (2X,I5,3X,10A1,20X,80A1)
      WRITE (IOFILE,1002) ICARD,NCERS,(ISOUR(K),K=1,KL)
C
C
 100  CONTINUE
      NLINE = NLINE + 1
      RETURN
      END
      SUBROUTINE LOADOP
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
C
C
      CALL IFILE (INFILE, 'OPTAP')
      NSYM=0
 10   CONTINUE
      CALL NEXTCD
      IF (EOFLG) GO TO 20
      CALL GETSYM(NAME)
      IF( NAME .EQ. 0 ) GO TO 20
      CALL SKPBLK
      IRADIX = 8
      CALL GETNUM( IVAL, IT)
      CALL SKPBLK
      IRADIX = 10
      CALL GETNUM( ITYP, IT)
       ITYP = ITYP + 32
      CALL ADDSYM( NAME, IVAL, ITYP)
      GO TO 10
C
20    CONTINUE
      CALL ADDSYM( IEQLS,  160,  24 + 32 )
      PUNCH 9100 , NSYM
 9100 FORMAT (6X,12HDATA NSYM / I5 , 3H /  )
      DO 101 I=1,NSYM
      PUNCH 9000,    I,I,I,SYNAME(I),SYVALU(I),SYTYPE(I)
 9000 FORMAT (6X,12HDATA SYNAME(  ,I3, 9H),SYVALU(  ,I3,9H),SYTYPE(  ,
     *I3,3H) / ,I12,1H, ,I6, 1H,,I3,1H/)
  101 CONTINUE
      ENDFILE INFILE
      RETURN
      END
      SUBROUTINE LOCATS( IV, ITP )
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
C
C
C
C			     J	 1=LOC, 2=NREL,3=ZREL
C			     PROCESS .LOC .NREL .ZREL
C			     SET OUTPUT TYPE
      IOCLAS = 4
      NWDS = 0
      IWTYPE = 1
      IF( SKPFLG ) RETURN
      IOCLAS = 3
      J = IAND( IV,7)
      IF( J.GT. 1 ) GO TO 20
C			     GET WHICH OF 3 OPS
C			     .LOC
C			     EVALUATE EXPRESSION
      CALL EXPRES(IX, IT, MO)
      IF( IT.LE.0 .OR. IT.GT.3 .OR. MO.NE.1 ) GO TO 50
C			     IF( ZREL .AND. IX.GT.377 )
      IF( IT.EQ.3 .AND. IX.GE.256 ) GO TO 50
C			     IF( EXP IS NEG OR.GT. CORE SIZE )
      IF( IX.LT.0 .OR. IX.GT.ICORE ) GO TO 50
C			     SET UP LOCATION COUNTER
      J = IT
      IF( IX.LT.LOCS(IT) ) CALL ERROR( 1HL )
      LOCS(IT) = MAX0(LOCS(IT), IX )
   20 CONTINUE
      IMODE = J
      IF(IMODE .NE. 1 ) RELASM = .TRUE.
      LOCCNT = LOCS(IMODE)
      LOCNXT = LOCCNT
      CALL CAREND
      IF( LABEL .NE. 0 ) CALL ADDSYM( LABEL, LOCCNT, IMODE )
      IWTYPE = IMODE
      IWORD(1) = LOCCNT
      RETURN
C			     ERROR SET ADDRESS = 0  MODE = ABS
   50 CONTINUE
      CALL ERROR( 1HL )
      J = 1
      GO TO 20
      END
      SUBROUTINE LOOKUP( NAME, IVALUE, ITYPE)
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
C
C
      DIMENSION MODT9(7),MODTV(7)
      DATA  NMODT9/7/, MODT9/3,15,26,12,18,19,0/
C			     C,O,Z,L,R,S,BLANK
      DATA MODTV	     /48,32,16,64,128,192,0/
      COMMON /REFER/ I
      LOGICAL INO
      DATA MASK / O777777000000 /
C			     LOOK UP A SYMBOL NAME IN SYMBOL TABLE
C			     RETURN VALUE AND TYPE. LOOK FOR ALC (TYPE8)
C			     INSTS. FIRST. IF UNDEF RETURN TYPE = 0
C			     ALSO IF TYPE 1 PROCESS NO LOAD CHAR
C			     IF SYM HAS MORE THAN 3 CHARS MAY BE ALC
      IF( NLNX .GT. 3 ) GO TO 50
C			     SYM MUST APPEAR IDENTICALLY IN SYM TABLE
    5 CONTINUE
      CALL LOSK( NAME, I, INO )
      IF( INO ) GO TO 20
C			     NOT IN TABLE  IE UNDEF
      IVALUE = 0
      ITYPE = 1
      CALL ERROR( 1HU )
      RETURN
C
C			     FOUND IN TABLE SET VALUE AND TYPE
   20 CONTINUE
      IVALUE = SYVALU(I)
   25 CONTINUE
      ITX = SYTYPE(I)
      ITYPE = IAND(ITX, 31)
C			     IF( .NOT.(ALC .AND. BREAK IS NO-LEAD))RET
      IF( ITYPE.NE.9 .OR. INOLOD.EQ.0 ) RETURN
C
C
C			     ALC AND NOLOAD SO INSERT 10 OCTAL AND ADV.
      IVALUE = IOR( IVALUE, 8)
      RETURN
C
C			     LOOK FOR ALC INST. WITH MODIFIERS
C			     IF( MORE THAN 5 CHARS IN SYM ) NOT ALC
   50 CONTINUE
      IF( NLNX .GT. 5 ) GO TO 5
      IX=IAND(NAME,MASK)
C			     SEARCH FOR TOP 3 CHARS OF SYMBOL IN TABLE
      CALL LOSK( IX, I, INO )
      IF( INO ) GO TO 60
C			     NOT IN TABLE GO LOOK UP LONG
      GO TO 5
C			     FOUND IN TABLE  SO SET VALUE AND TYPE
   60 CONTINUE
C
      IVALUE = SYVALU(I)
      ITX = SYTYPE(I)
      IF( IAND(ITX, 31) .NE. 9 ) GO TO 5
C			     NOW LOOK UP  4-TH AND POSSIBLY 5-TH CHARS
C			     AS ALC MODIFIERS
C
      NSHFT = 0
      NCRRY = 0
C
C
      DO  70  K=1,NMODT9
      IF( LNX(4) .EQ. MODT9(K) ) GO TO 73
 70   CONTINUE
      GO TO 5
C			     IF CHAR NOT IN MOD. LIST GO LOOK UP LONG
   73 CONTINUE
C			     INSERT PROPER BIT
      IF( ( K .GE. 1 ) .AND. (K .LE. 3 ) ) NCRRY = NCRRY + 1
      IF( ( K .GE. 4 ) .AND. ( K .LE. 6 ) ) NSHFT = NSHFT + 1
      IK = K
      IF (NLNX .EQ. 4) GO TO 76
C
      DO 74 K = 4,NMODT9
      IF (LNX(5) .EQ. MODT9(K)) GO TO 75
   74 CONTINUE
      GO TO 5
C
   75 NSHFT = NSHFT + 1
      IF( NSHFT .GT. 1 ) GO TO 5
      IVALUE = IOR( IVALUE, MODTV(K) )
  76  IVALUE = IOR (IVALUE, MODTV(IK))
C			     ALL DONE  NOW GO TO CHECK NO LOAD
      GO TO 25
      END
      SUBROUTINE LOSK(NAME, NPOS, LNO )
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
C
C
      LOGICAL LNO
C			     LOSK SEARCHES THE SYMBOL TABLE TO FIND NAME
C			     IF NAME IS FOUND NPOS IS SET EQUAL TO NAMES
C			     POSITION IN THE TABLE. IF NOT FOUND NPOS IS
C			     SET TO THE POSITION WHERE IT SHOULD BE
      NPOS =0
C			     START IN THE MIDDLE OF THE TABLE
      NR=NSYM/2
      IF(NR.LT.1) NR=1
      ISIGN=1
      KSIGN=0
      LNO=.TRUE.
  100 CONTINUE
      NPOS=NPOS + ISIGN*NR
      IF((NPOS.GT.NSYM).OR.(NPOS.LE.0)) GO TO 400
      IF(NR.EQ.1) KSIGN=ISIGN
      NR=NR/2
      IF(NR.LT.1) NR=1
C			     WHICH DIRECTION SHOULD WE GO
      ISIGN=1
      IF(NAME-SYNAME(NPOS)) 110,500,120
  110 CONTINUE
      ISIGN=-1
  120 CONTINUE
C			     HAS THE UNIT SEARCH REVERSED DIRECTION
      IF(KSIGN*ISIGN.GE.0) GO TO 100
  400 CONTINUE
      LNO=.FALSE.
      IF( NPOS.LE.0 .OR. KSIGN.LT.0 ) NPOS = NPOS + 1
  500 CONTINUE
      IF( NPOS.GT.1 .AND. NAME.EQ.SYNAME(NPOS-1) ) NPOS = NPOS-1
      RETURN
      END
      SUBROUTINE MORTXT
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
      COMMON /TXTBLK/ JSVE,IJ,LCHAR,TXTMOD,LSVE
      LOGICAL TXTMOD
C
      DATA MBTS /127 /
      IOCLAS = 2
C
CLOOK FOR LAST SIGNIFICANT CHARACTER IN THIS LINE
C
      CALL STOPSP(KL)
      J = 1
      L = LSVE
      IWORD(1) = JSVE
      GO TO 10
C
C
    5 CONTINUE
      L = 8
      IWORD(J) = 0
   10 CONTINUE
      ICH = ICH+1
      M = LN(ICH)
      IF( M.EQ.LCHAR ) GO TO 20
      IF ((M.GE.64) .OR. (ICH.GT.KL)) GO TO 30
      IF( M .NE. ILAGL ) GO TO 11
      ICH = ICH+1
      IRDX=IRADIX
      IRADIX=8
      CALL EXPRES( IX,ITP, MO)
      IRADIX=IRDX
      IF( ITP.NE.1 .OR. MO.NE.1 ) CALL ERROR(1HX)
      IV = IAND( IX, MBTS)
      CALL SKPBLK
      IF( LN(ICH).NE.IRAGL ) CALL ERROR(1HX)
      GO TO 13
   11 CONTINUE
      IV = IASCII(M)
   13 CONTINUE
      INOR = 0
      GO TO( 18, 17, 16, 15),IJ
   15 CONTINUE
      INOR = 128
      GO TO 18
   16 IF( IPARTY(IV) .EQ. 0 ) INOR = 128
      GO TO 18
   17 IF( IPARTY(IV) .EQ. 1 ) INOR = 128
   18 CONTINUE
      IV = IOR( IV,INOR)
      IF( TXTMOD ) GO TO 19
      IWORD(J) = IOR(IWORD(J), ILEFT(IV,MOD(L+8,16)))
      GO TO 191
   19 CONTINUE
      IWORD(J) = IOR(IWORD(J),ILEFT(IV,L))
  191 CONTINUE
      L = L-8
      IF( L .GE. 0 ) GO TO 10
      J = J+1
      GO TO 5
   20 CONTINUE
      TXTFLG = .FALSE.
      NWDS = J
C
CFOUND END OF TEXT, RETURN
C
      RETURN
C
C
   30 CONTINUE
      JSVE = IWORD(J)
      LSVE = L
      IF (J.EQ.1) IOCLAS = 4
      NWDS = J-1
      RETURN
      END
      SUBROUTINE NEXTCD
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
      COMMON / FILNM / INAME,IONAME
      COMMON /CSEQ/ SEQ
      LOGICAL SEQ
C
C
      DIMENSION JALL(5)
      DATA JALL/' ','.','E','N','D' /
      ICH = 1
      IF (SEQ) ICH=7
      ICARD = ICARD +1
      IF( EOFLG ) GO TO 20
      READ( INFILE, 1000,ERR= 50,END= 20) (LN(I),I=1,80)
 1000 FORMAT( 80A1 )
   10 DO 5 I=1,80
    5 ISOUR(I) = LN(I)
  N(81) = 64
      CALL CONVRT( LN )
      RETURN
   20 CONTINUE
      EOFLG = .TRUE.
      DO  25 I=1,80
   25 LN(I) = JALL(1)
      LN(6) = JALL(2)
      LN(7) = JALL(3)
      LN(8) = JALL (4)
      LN(9) = JALL(5)
      TXTFLG = .FALSE.
      GO TO 10
 50   CONTINUE
      TYPE 1001, ICARD,INAME
 1001 FORMAT(5X' *** ERROR ON INPUT LINE'  I6, ' ON FILE'  A5 ,' ***'/)
      STOP
      END
      SUBROUTINE NEXTNM( NAME )
C
C
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
C
C			     RETURN THE NEXT NAME IN THE LIST
C			     IF NO MORE RETRUN 0
C			     IF FIRST ENTRY NAME IS 0
      IF( LN(ICH) .EQ. ICOMA ) ICH = ICH + 1
C
      CALL GETSYM( NAME )
      IF( NAME .NE. 0 ) RETURN
      IF( LN(ICH) .EQ.ISEMI .OR. LN(ICH).EQ.64 ) RETURN
C
      CALL ERROR(1HG)
      RETURN
      END
      SUBROUTINE NONOLD
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
      IF( INOLOD .NE. 0 ) CALL ERROR(1H#)
      RETURN
      END
      SUBROUTINE NOTAT
      COMMON NREF,ICH,NLNX,IMODE,LOCCNT,LOCNXT,ICORE,IRADIX,LABEL
     1,INDRCT,NLINE,IPAGE,NCER,NEREF,IOCLAS,ICARD,NWDS,IWTYPE,IRELO
     2,NRELO,IWDCT,IADL,INOLOD,ITITLE,RELASM,XREF,PASS1
     3,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG,ANYPCH,CODE,LOCALS
     4,CROSS(3,1000),LN(81),LNX(81)
     5,ISOUR(80),NEREFS(50),NCERS(10),IWORD(40),IBL(22),LOCS(3)
      COMMON /CDS/ INFILE,IOFILE,IPFILE,ISCR
     1,LETA,LETB,LETC,LETD,LETE,LETZ,INU0,INU9,IPRD,IPLUS,ISEMI,IEQLS
     2,ICOLN,IBLNK,IRAGL,ILAGL,IAT,INLOD,ICOMA,ICLAS(7)
      LOGICAL RELASM,XREF,PASS1,PTAPE,SKPFLG,IFMODE,EOFLG,TXTFLG,ERRFLG
     1	  ,ANYPCH,CODE,LOCALS
      COMMON /LIMITS/ NSYMX,NREFX,NLINEX,NCERX,NEREFX
      COMMON / SYMTB / SYNAME(1000),SYVALU(1000),SYTYPE(1000),NSYM
      INTEGER SYNAME,SYTYPE,SYVALU,CROSS
C
      IF( INDRCT .NE. 0 ) CALL ERROR(1H@ )
      RETURN
      END
      SUBROUTINE OBIT( IVALUE,NTOP,NBITS,IRSLT)
      IX = ILEFT(IVALUE,36-NTOP)
      IRSLT = IRIGHT( IX,36-NBITS)
      RETURN
      END
@a©