;JOB%1(17) TO MAKE PLEASE.SAV FROM PLEASE.MAC
;SUBMIT WITH COMMAND  .QUEUE I:=PLEASE/RESTART:1
;
;REQUIRED FILES:  (LATEST RELEASED VERSIONS)
;[10,7]	PIP.SHR
;	DIRECT.SHR
;	COMPIL.SHR
;	MACRO.SHR
;	LOADER.SHR
;	CREF.SHR
;[SELF]	PLEASE.MAC
;
;OUTPUT FILE:
;	PLEASE.SAV
;OUTPUT LISTINGS:
;	PLEASE  MAP
;	PLEASE  CREF LISTING
;	PLEASE.LOG
;
;
;THE ONLY ASSEMBLY OPTION IS 
;	TTYNUM==<SIXBIT /TTY0/>
;		TO SET THE DEFAULT TTY NUMBER
;
;
;COPY FILES FROM [10,7] AND USE PRIVATE "SYS:"
.RUN DSK:PIP[10,7]
*/X_DSK:PIP.SHR[10,7],COMPIL.SHR[10,7],MACRO.SHR[10,7],LOADER.SHR[10,7]
*/X_DSK:CREF.SHR[10,7]
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=*.SHR
.GOTO A
A:.RUN DSK: DIRECT[10,7]
*TTY:/CHECKSUM=*.MAC
.ASSIGN DSK: SYS:
;
;COMPILE, LOAD, AND SAVE; PRODUCING MAP AND CREF FILE
.LOAD /MAP:LPT:PLEASE /CREF /COMPILE PLEASE.MAC
.SAVE DSK:PLEASE
.VERSION
.IF (ERROR) .E 137
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=PLEASE.SAV
;
;PRODUCE SOURCE LISTING AND TELL OPERATOR
.CREF
.PLEASE PLEASE SUCCESSFUL
;
;REMOVE ALL TEMPORARY FILES
%FIN: .DELETE PLEASE.REL,MACRO.SHR,LOADER.SHR,CREF.SHR
.IF (ERROR) ;DON'T CARE IF FAILED
.DELETE COMPIL.SHR,PIP.SHR
