; SUBROUTINE SHIFT (INWD,SCOUNT,OUTWD)
;

; SHIFT A WORD LEFT OR RIGHT
;
; INWD=WORD TO BE SHIFTED
; SCOUNT=# BITS TO SHIFT - SHIFT RIGHT IF NEGATIVE
; OUTWD=RESULT
;
        TITLE   SHIFT
        ENTRY   SHIFT
;
        SCOUNT=1
        W1=2
SHIFT:  0
        MOVE    SCOUNT,@1(16)
        HRRM    SCOUNT,SH10
        MOVE    W1,@0(16)
SH10:   LSH     W1,.-.
        MOVEM   W1,@2(16)
        JRA     16,3(16)
        END
