TITLE SIZE OF RANDOM FILE

ENTRY   SIZE

EXTERN  FILSZ.

IFNDEF REENT,<REENT==0>
IFN REENT,<LOW=16>
IFE REENT,<LOW=0>

A=1
Q=16
P=17

SIZE:   0
        PUSH    P,A             ;GET A REGISTER
        MOVE    A,@(Q)          ;GET F4 UNIT
IFN REENT,<ADDI A,(LOW)>
        MOVE    0,FILSZ.(A)     ;GET FILE SIZE
        POP     P,A             ;RESTORE REGISTER
        JRA     Q,1(Q)          ;RETURN

        END
