;JOB %1(20) TO MAKE SPACE.SAV FROM SPACE.MAC
;SUBMIT WITH COMMAND  .QUEUE I:=SPACE/RESTART:1
;
;REQUIRED FILES:  (LATEST RELEASED VERSIONS)
;[10,7]	PIP.SHR
;	DIRECT.SHR
;	COMPIL.SHR
;	MACRO.SHR
;	LOADER.SHR
;	JOBDAT.REL
;	CREF.SHR
;	C.MAC
;	QUEUER.REL
;	HELPER.REL
;[SELF]	SPACE.MAC
;
;OUTPUT FILE:
;	SPACE.SAV
;OUTPUT LISTINGS:
;	SPACE  MAP
;	SPACE  CREF LISTING
;	SPACE.LOG
;
;
;COPY FILES FROM [10,7] AND USE PRIVATE "SYS:"
.RUN DSK:PIP[10,7]
*/X_DSK:PIP.SHR[10,7],COMPIL.SHR[10,7],MACRO.SHR[10,7],LOADER.SHR[10,7]
*/X_DSK:JOBDAT.REL[10,7],CREF.SHR[10,7],C.MAC[10,7],QUEUER.REL[10,7]
*/X_DSK:HELPER.REL[10,7]
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=*.SHR
.GOTO A
A:.RUN DSK: DIRECT[10,7]
*TTY:/CHECKSUM=*.MAC+*.REL+*.DOC+*.RND+*.HLP+*.CTL
.ASSIGN DSK: SYS:
;
;COMPILE, LOAD, AND SAVE; PRODUCING MAP AND CREF FILE
.LOAD /MAP:LPT:SPACE /CREF /COMPILE C+SPACE.MAC,QUEUER.REL%H,HELPER.REL%H %A
.SAVE DSK:SPACE
.VERSION
.IF (ERROR) .E 137
;
;TRY IT JUST TO MAKE SURE IT WORKS
.RUN DSK:SPACE
*/HELP
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=SPACE.SAV+SPACE.HLP
;
;PRODUCE SOURCE LISTING AND TELL OPERATOR
.CREF
.PLEASE SPACE SUCCESSFUL
;
;REMOVE ALL TEMPORARY FILES
%FIN: .DELETE SPACE.REL,MACRO.SHR,C.MAC,QUEUER.REL,LOADER.SHR,CREF.SHR
.IF (ERROR) ;DON'T CARE IF FAILED
.DELETE COMPIL.SHR,PIP.SHR,JOBDAT.REL,HELPER.REL
