;****THIS FILE CREATES THE CORRECTION FILE FOR DISTRIBUTION******
;
;
;*******THE OLD SOURCE SHOULD BE ON [10,7]
;
;
;[10,7]	SPOOL.MAC
;	CAM.LOW
;	CAM.LOW
;	PIP.SHR
;	DIRECT.SHR
;
;[SELF]	SPOOL.MAC
;	SPOOL.DOC
;
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=[10,7]SPOOL.MAC,CAM.*,PIP.*,DIRECT.*,FILCOM[10,7].*
.RUN DSK:FILCOM[10,7]
*LPT:_SPOOL.MAC,SPOOL.MAC[10,7]
.RUN DSK:CAM[10,7]
*DSK:SPOOL.COR,LPT,TTY:_DSK:SPOOL.MAC[10,7],DSK:SPOOL.MAC
.RUN DSK:PIP[10,7]
*DSK:SPOOL.COR_DSK:SPOOL.COR,TTY:,DSK:SPOOL.DOC,TTY:,DSK:SPOOL.CTL
*-!SPOOL.DOC_
=^Z
*-!SPOOL.CTL_
=^Z
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUC=*.DOC,*.CTL,*.COR
.PLEASE SPOOL SUCCESSFUL
