;JOB%1(16) TO MAKE SYSDPY.SAV, ETC., FROM SYSDPY.MAC
;SUBMIT WITH COMMAND  .QUEUE I:=SYSDPY/RESTART:1/TIME:20:0
;
;REQUIRED FILES:  (LATEST RELEASED VERSIONS)
;[10,7]	PIP.SHR
;	DIRECT.SHR
;	COMPIL.SHR
;	MACRO.SHR
;	LOADER.SHR
;	JOBDAT.REL
;	CREF.SHR
;	C.MAC
;[SELF]	SYSDPY.MAC
;
;OUTPUT FILES:
;	SYSDPY.SAV	FOR VT06
;	SYSDPA.SAV	FOR VT05A
;	SYSDPB.SAV	FOR VT05B
;OUTPUT LISTINGS:
;	SYSDPY  MAP
;	SYSDPA  MAP
;	SYSDPB  MAP
;	SYSDPY  CREF LISTING
;	SYSDPA  CREF LISTING
;	SYSDPB  CREF LISTING
;	SYSDPY.LOG
;
;
;COPY FILES FROM [10,7] AND USE PRIVATE "SYS:"
.RUN DSK:PIP[10,7]
*/X_DSK:PIP.SHR[10,7],COMPIL.SHR[10,7],MACRO.SHR[10,7],LOADER.SHR[10,7]
*/X_DSK:JOBDAT.REL[10,7],CREF.SHR[10,7],C.MAC[10,7]
;
;MAKE A RECORD OF WHAT IS BEING USED
.SET WATCH VERSION
.IF (NOERROR) .GOTO A
.RUN DSK:DIRECT[10,7]
*TTY:/CHECKSUM=*.SAV+*.SHR+*.HLP
.GOTO A
A:.RUN DSK: DIRECT[10,7]
*TTY:/CHECKSUM=*.MAC+*.REL+*.CTL
.ASSIGN DSK: SYS:
;
;COMPILE, LOAD, AND SAVE; PRODUCING MAP AND CREF FILE
.RUN DSK: PIP[10,7]
*SYSDPY.TMP=TTY:
*V.DISP==0	;VT06
^Z
.LOAD /MAP:LPT:SYSDPY /CREF /COMPILE C.MAC+SYSDPY.TMP+SYSDPY.MAC %A
.SAVE DSK:SYSDPY
.VERSION
.IF (ERROR) .E 137
.LOAD /MAP:LPT:SYSDPA /CREF /COMPILE SYSDPA=C.MAC+SYSDPY.MAC %A
.SAVE DSK:SYSDPA
.VERSION
.IF (ERROR) .E 137
.RUN DSK: PIP[10,7]
*SYSDPY.TMP=TTY:
*V.DISP==2	;VT05B
^Z
.LOAD /MAP:LPT:SYSDPB /CREF /COMPILE SYSDPB=C.MAC+SYSDPY.TMP+SYSDPY.MAC %A
.SAVE DSK:SYSDPB
.VERSION
.IF (ERROR) .E 137
.RU DSK: DIRECT[10,7]
*TTY:/CHECKSUM=SYSDP?.SAV+SYY???.RND
;
;PRODUCE SOURCE LISTING AND TELL OPERATOR
.CREF
.PLEASE SYSDPY SUCCESSFUL
;
;REMOVE ALL TEMPORARY FILES
%FIN: .DELETE SYSDP?.REL,MACRO.SHR,LOADER.SHR,CREF.SHR
.IF (ERROR) ;DON'T CARE IF FAILED
.DELETE COMPIL.SHR,PIP.SHR,JOBDAT.REL,C.MAC,SYSDPY.TMP
